/*
 * Regenerates the derived copies of the core from src/:
 *   docs/md2org.js           the browser page
 *   docs/md2org-entities.js  the browser page, with character-reference decoding
 *   shortcut/transform.js    the iOS Shortcut, using the Actions $text/return convention
 *
 * Each module in src/ marks its shipped part with "core start" and "core end"
 * markers. The marked regions are concatenated in dependency order into one scope
 * with no module system; everything outside them is dropped.
 *
 * Run `node build.js` after editing src/. `npm test` fails if the copies are stale.
 */
const fs = require("fs");
const wrapLines = require("./tools/wrap-lines.js");
const esbuild = require("esbuild");
const vm = require("vm");

/*
 * Prefix on a Shortcut result that reports a failure rather than converted text.
 * No Org output can begin with it.
 */
const ERROR_SENTINEL = "\u26A0\uFE0F md2org:";

/*
 * Minifies the Shortcut copy, which is limited by the Actions code field (see
 * DESIGN.md, Constraints). The forked parser is already minified, so this affects
 * only src/. The browser copy is left readable.
 */
function minify(src) {
  const r = esbuild.transformSync(src, { minify: true, lineLimit: 400, loader: "js" });
  return r.code;
}

/*
 * Removes whole-line comments and blank lines from the derived copies. Trailing
 * comments are left, since removing them safely needs a real parser. Both copies
 * are run against the full test corpus below, so a stripping error fails the build.
 */
function stripComments(src) {
  const out = [];
  let inBlock = false;
  for (const line of src.split("\n")) {
    const t = line.trim();
    if (inBlock) {
      if (t.endsWith("*/")) inBlock = false;
      continue;
    }
    if (t.startsWith("/*")) {
      if (!t.endsWith("*/")) inBlock = true;
      continue;
    }
    if (t.startsWith("//")) continue;
    if (t === "") continue;
    out.push(line);
  }
  return out.join("\n") + "\n";
}

const START = "/* --8<-- core start */";
const END = "/* --8<-- core end */";

function core(path) {
  const s = fs.readFileSync(path, "utf8");
  const a = s.indexOf(START);
  const b = s.indexOf(END);
  if (a === -1 || b === -1) throw new Error("missing core markers in " + path);
  return s.slice(a + START.length, b).trim();
}

// The forked parser is a self-contained IIFE assigning to __cmark; only its
// CommonJS tail is removed.
function vendor(path) {
  return fs.readFileSync(path, "utf8")
    .replace(/\nif \(typeof module[\s\S]*?\}\n?$/, "")
    .trim();
}

/*
 * Removes leading indentation from our own modules, saving about 1.7 KB. Not
 * applied to the forked parser, whose template literals could span lines. Our
 * sources must contain no backticks, which is asserted.
 */
function deindent(src) {
  if (src.indexOf("`") !== -1) {
    throw new Error("deindent: source contains a template literal; not safe to strip indentation");
  }
  return src.split("\n").map(l => l.replace(/^[ \t]+/, "")).join("\n");
}

const parts = [
  vendor("src/vendor/commonmark.js"),
  deindent(core("src/org-escape.js")),
  deindent(core("src/org-render.js")),
  deindent(core("src/md2org.js"))
];

const banner =
  "/*\n" +
  " * md2org — generated by build.js from src/. Do not edit this file directly.\n" +
  " * Edit src/ and run `node build.js`.\n" +
  " */\n";

// Wrap long lines, which can crash the Shortcuts editor. esbuild's lineLimit
// handles most; wrapLines handles the rest.
const bundle = wrapLines(stripComments(parts.join("\n\n")), 400);

// 1. web copy: the bundle plus the universal export tail
fs.writeFileSync(
  "docs/md2org.js",
  banner + bundle +
  "\n\nif (typeof module !== \"undefined\" && module.exports) {\n" +
  "  module.exports = md2org;\n  module.exports.md2org = md2org;\n}\n" +
  "if (typeof window !== \"undefined\") {\n  window.md2org = md2org;\n}\n"
);

/*
 * 1b. web copy with character-reference decoding, for the page's checkbox.
 *
 * Built from the same src/ over the parser that carries upstream's entity table.
 * Wrapped in its own scope and exposing only window.md2orgEntities, so it is
 * independent of the first bundle. The page loads it only when the option is
 * selected. Never built into the Shortcut copy, which cannot hold the table.
 */
const entitiesBundle = wrapLines(stripComments([
  vendor("src/vendor/commonmark-entities.js").replace(/\bvar __cmarkEntities=/, "var __cmark="),
  deindent(core("src/org-escape.js")),
  deindent(core("src/org-render.js")),
  deindent(core("src/md2org.js"))
].join("\n\n")), 400);

fs.writeFileSync(
  "docs/md2org-entities.js",
  banner +
  "// Character references decoded to the characters they name. Loaded on demand\n" +
  "// by docs/index.html when the box is ticked; md2org proper is docs/md2org.js.\n" +
  "(function () {\n" + entitiesBundle + "\n" +
  "if (typeof window !== \"undefined\") { window.md2orgEntities = md2org; }\n" +
  "if (typeof module !== \"undefined\" && module.exports) { module.exports = md2org; }\n" +
  "})();\n"
);

// 2. shortcut copy: a function body; input arrives as $text and the result is
// returned.
//
// A throw in this action yields no output, which is indistinguishable from an
// empty conversion, so failures are returned as text beginning with
// ERROR_SENTINEL. The Shortcut branches on that prefix to show an alert.
fs.writeFileSync(
  "shortcut/transform.js",
  // The version identifies which build was pasted when diagnosing a failure.
  "// transform.js, md2org " + require("./package.json").version + "\n" +
  minify(bundle) + "\n" +
  "try{var i=$text==null?\"\":String($text);" +
  "if(i==\"\")return " + JSON.stringify(ERROR_SENTINEL + " no input — set the Text field to Clipboard") + ";" +
  "var o=md2org(i);" +
  "return o==\"\"?" + JSON.stringify(ERROR_SENTINEL + " result was empty") + ":o}" +
  "catch(e){return " + JSON.stringify(ERROR_SENTINEL + " ") + "+(e&&e.message||e)}\n"
);

// 3. verify parity
const md = require("./src/md2org.js");
const shortcutFn = new Function("$text", fs.readFileSync("shortcut/transform.js", "utf8"));
delete require.cache[require.resolve("./docs/md2org.js")];
const webFn = require("./docs/md2org.js");
// The corpus from test/spec.js, so every construct the suite covers is checked.
const probes = require("./test/corpus.js");
for (const s of probes) {
  if (md(s) !== webFn(s)) throw new Error("docs/md2org.js drifted");
  // Empty input returns a hint in the Shortcut copy rather than an empty
  // string. Every other input must match src/ exactly.
  if (s === "") {
    if (shortcutFn(s).indexOf(ERROR_SENTINEL) !== 0) {
      throw new Error("shortcut/transform.js lost its empty-input guidance");
    }
    continue;
  }
  if (md(s) !== shortcutFn(s)) throw new Error("shortcut/transform.js drifted");
}

/*
 * The entities copy is checked against md2org.withEntities over the same corpus.
 */
const entitiesFn = (() => {
  const c = vm.createContext({ window: {}, module: { exports: {} } });
  vm.runInContext(fs.readFileSync("docs/md2org-entities.js", "utf8"), c);
  return vm.runInContext("window.md2orgEntities", c);
})();
for (const s of probes) {
  if (md.withEntities(s) !== entitiesFn(s)) throw new Error("docs/md2org-entities.js drifted");
}

console.log("build ok — docs/md2org.js, docs/md2org-entities.js and " +
            "shortcut/transform.js regenerated and verified");
