// transform.js, md2org 1.1.0
var __cmark=(()=>{var f=Object.create,m=Object.defineProperty,G=Object.getOwnPropertyDescriptor,et=Object.getOwnPropertyNames,ot=Object.getPrototypeOf,U=Object.prototype.hasOwnProperty,z=(t,e,n)=>()=>{if(n)throw n[0];try{return t&&(e=t(t=0)),e}catch(i){throw n=[i],i}},F=(t,e)=>()=>{try{return e||t((e={exports:{}}).exports,e),e.exports}catch(n){throw e=0,n}},Lt=(t,e)=>{for(var n in e)m(t,n,{get:e[n],
enumerable:!0})},ct=(t,e,n,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of et(e))!U.call(t,r)&&r!==n&&m(t,r,{get:()=>e[r],enumerable:!(i=G(e,r))||i.enumerable});return t},N=(t,e,n)=>(n=t!=null?f(ot(t)):{},ct(e||!t||!t.__esModule?m(n,"default",{value:t,enumerable:!0}):n,t)),v=t=>ct(m({},"__esModule",{value:!0}),t);function ht(t){switch(t._type){case"document":case"block_quote":case"\
list":case"item":case"paragraph":case"heading":case"emph":case"strong":case"strikethrough":case"table":case"table_row":case"table_cell":case"footnote_definition":case"link":case"image":case"custom_inline":case"custom_block":return!0;default:return!1}}var $,Q,ut,D,k,_,Nt=z(()=>{"use strict";$=function(t,e){this.current=t,this.entering=e===!0},Q=function(){var t=this.current,e=this.entering;if(t===null)
return null;var n=ht(t);return e&&n?t._firstChild?(this.current=t._firstChild,this.entering=!0):this.entering=!1:t===this.root?this.current=null:t._next===null?(this.current=t._parent,this.entering=!1):(this.current=t._next,this.entering=!0),{entering:e,node:t}},ut=function(t){return{current:t,root:t,entering:!0,next:Q,resumeAt:$}},D=function(t,e){this._type=t,this._parent=null,this._firstChild=null,
this._lastChild=null,this._prev=null,this._next=null,this._sourcepos=e,this._open=!0,this._string_content=null,this._literal=null,this._listData={},this._info=null,this._destination=null,this._title=null,this._isFenced=!1,this._fenceChar=null,this._fenceLength=0,this._fenceOffset=null,this._level=null,this._onEnter=null,this._onExit=null},k=D.prototype,Object.defineProperty(k,"isContainer",{get:function(){
return ht(this)}}),Object.defineProperty(k,"type",{get:function(){return this._type}}),Object.defineProperty(k,"firstChild",{get:function(){return this._firstChild}}),Object.defineProperty(k,"lastChild",{get:function(){return this._lastChild}}),Object.defineProperty(k,"next",{get:function(){return this._next}}),Object.defineProperty(k,"prev",{get:function(){return this._prev}}),Object.defineProperty(
k,"parent",{get:function(){return this._parent}}),Object.defineProperty(k,"sourcepos",{get:function(){return this._sourcepos}}),Object.defineProperty(k,"literal",{get:function(){return this._literal},set:function(t){this._literal=t}}),Object.defineProperty(k,"destination",{get:function(){return this._destination},set:function(t){this._destination=t}}),Object.defineProperty(k,"title",{get:function(){
return this._title},set:function(t){this._title=t}}),Object.defineProperty(k,"info",{get:function(){return this._info},set:function(t){this._info=t}}),Object.defineProperty(k,"level",{get:function(){return this._level},set:function(t){this._level=t}}),Object.defineProperty(k,"listType",{get:function(){return this._listData.type},set:function(t){this._listData.type=t}}),Object.defineProperty(k,"lis\
tTight",{get:function(){return this._listData.tight},set:function(t){this._listData.tight=t}}),Object.defineProperty(k,"listStart",{get:function(){return this._listData.start},set:function(t){this._listData.start=t}}),Object.defineProperty(k,"listDelimiter",{get:function(){return this._listData.delimiter},set:function(t){this._listData.delimiter=t}}),Object.defineProperty(k,"onEnter",{get:function(){
return this._onEnter},set:function(t){this._onEnter=t}}),Object.defineProperty(k,"onExit",{get:function(){return this._onExit},set:function(t){this._onExit=t}}),D.prototype.appendChild=function(t){t.unlink(),t._parent=this,this._lastChild?(this._lastChild._next=t,t._prev=this._lastChild,this._lastChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.prependChild=function(t){t.unlink(),t._parent=
this,this._firstChild?(this._firstChild._prev=t,t._next=this._firstChild,this._firstChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.unlink=function(){this._prev?this._prev._next=this._next:this._parent&&(this._parent._firstChild=this._next),this._next?this._next._prev=this._prev:this._parent&&(this._parent._lastChild=this._prev),this._parent=null,this._next=null,this._prev=null},D.prototype.
insertAfter=function(t){t.unlink(),t._next=this._next,t._next&&(t._next._prev=t),t._prev=this,this._next=t,t._parent=this._parent,t._next||(t._parent._lastChild=t)},D.prototype.insertBefore=function(t){t.unlink(),t._prev=this._prev,t._prev&&(t._prev._next=t),t._next=this,this._prev=t,t._parent=this._parent,t._prev||(t._parent._firstChild=t)},D.prototype.walker=function(){var t=new ut(this);return t},
_=D}),pt=F((t,e)=>{"use strict";var n={};function i(s){var l,a,o=n[s];if(o)return o;for(o=n[s]=[],l=0;l<128;l++)a=String.fromCharCode(l),/^[0-9a-z]$/i.test(a)?o.push(a):o.push("%"+("0"+l.toString(16).toUpperCase()).slice(-2));for(l=0;l<s.length;l++)o[s.charCodeAt(l)]=s[l];return o}function r(s,l,a){var o,u,d,L,x,y="";for(typeof l!="string"&&(a=l,l=r.defaultChars),typeof a>"u"&&(a=!0),x=i(l),o=0,u=
s.length;o<u;o++){if(d=s.charCodeAt(o),a&&d===37&&o+2<u&&/^[0-9a-f]{2}$/i.test(s.slice(o+1,o+3))){y+=s.slice(o,o+3),o+=2;continue}if(d<128){y+=x[d];continue}if(d>=55296&&d<=57343){if(d>=55296&&d<=56319&&o+1<u&&(L=s.charCodeAt(o+1),L>=56320&&L<=57343)){y+=encodeURIComponent(s[o]+s[o+1]),o++;continue}y+="%EF%BF%BD";continue}y+=encodeURIComponent(s[o])}return y}r.defaultChars=";/?:@&=+$,-_.!~*'()#",r.
componentChars="-_.!~*'()",e.exports=r}),nt=F((t,e)=>{function n(i){return i}e.exports={decodeHTML:n,decodeHTMLStrict:n,encodeHTML:i=>i,escape:i=>i.replace(/[&<>"]/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[r])}}),Z,ft,dt,X,M,it,_t,gt,mt,rt,H,C,st,h,b,j,at,A,E,Bt,jt,vt,Et,Pt,O,c,kt,W,J=z(()=>{"use strict";Z=N(pt(),1),ft=N(nt(),1),dt=92,X="&(?:#x[a-f0-9]{1,6}|#[0-9]{1,7}|[a-z][a-z0-9]{\
1,31});",M="[A-Za-z][A-Za-z0-9-]*",it="[a-zA-Z_:][a-zA-Z0-9:._-]*",_t="[^\"'=<>`\\x00-\\x20]+",gt="'[^']*'",mt='"[^"]*"',rt="(?:"+_t+"|"+gt+"|"+mt+")",H="(?:\\s*=\\s*"+rt+")",C="(?:\\s+"+it+H+"?)",st="<"+M+C+"*\\s*/?>",h="</"+M+"\\s*[>]",b="<!-->|<!--->|<!--[\\s\\S]*?-->",j="[<][?][\\s\\S]*?[?][>]",at="<![A-Za-z]+[^>]*>",A="<!\\[CDATA\\[[\\s\\S]*?\\]\\]>",E="(?:"+st+"|"+h+"|"+b+"|"+j+"|"+at+"|"+A+
")",Bt=new RegExp("^"+E),jt=/[\\&]/,vt="[!\"#$%&'()*+,./:;<=>?@[\\\\\\]^_`{|}~-]",Et=new RegExp("\\\\"+vt+"|"+X,"gi"),Pt='[&<>"]',O=new RegExp(Pt,"g"),c=function(t){return t.charCodeAt(0)===dt?t.charAt(1):(0,ft.decodeHTMLStrict)(t)},kt=function(t){return jt.test(t)?t.replace(Et,c):t},W=function(t){try{return(0,Z.default)(t)}catch{return t}}});function lt(t){return K(t)}var K,S,wt,zt=z(()=>{"use st\
rict";String.fromCodePoint?K=function(t){try{return String.fromCodePoint(t)}catch(e){if(e instanceof RangeError)return"\uFFFD";throw e}}:(S=String.fromCharCode,wt=Math.floor,K=function(){var t=16384,e=[],n,i,r=-1,s=arguments.length;if(!s)return"";for(var l="";++r<s;){var a=Number(arguments[r]);if(!isFinite(a)||a<0||a>1114111||wt(a)!==a)return"\uFFFD";a<=65535?e.push(a):(a-=65536,n=(a>>10)+55296,i=
a%1024+56320,e.push(n,i)),(r+1===s||e.length>t)&&(l+=S.apply(null,e),e.length=0)}return l})});function $t(t){return{subject:"",delimiters:null,brackets:null,pos:0,refmap:{},match:Ne,peek:we,spnl:Oe,parseBackticks:De,parseBackslash:Ae,parseAutolink:Be,parseHtmlTag:je,scanDelims:Ee,handleDelim:Pe,parseLinkTitle:Se,parseLinkDestination:Te,parseLinkLabel:Re,parseOpenBracket:Ue,parseBang:Fe,parseCloseBracket:Ze,
addBracket:Me,removeBracket:He,parseEntity:Ie,parseString:qe,parseNewline:Ge,parseReference:Qe,parseInline:Xe,processEmphasis:$e,removeDelimiter:ze,options:t||{},parse:We}}var T,I,P,q,p,g,R,Y,St,bt,re,Ft,se,Zt,Tt,ae,V,tt,Rt,Mt,Ut,le,oe,Ht,ce,he,It,ue,pe,fe,de,_e,ge,me,ve,qt,Gt,ke,be,Qt,Ce,xe,ye,Le,w,Xt,Ne,we,Oe,De,Ae,Be,je,Ee,Pe,ze,Wt,$e,Se,Te,Re,Ue,Fe,Ze,Me,He,Ie,qe,Ge,Qe,Xe,We,Je,En=z(()=>{"use \
strict";Nt(),J(),zt(),T=N(nt(),1),I=W,P=kt,q=10,p=42,g=95,R=96,Y=91,St=93,bt=60,re=33,Ft=92,se=38,Zt=40,Tt=41,ae=58,V=39,tt=34,Rt=126,Mt=vt,Ut="\\\\"+Mt,le=X,oe=Bt,Ht=new RegExp(/^[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~\p{P}\p{S}]/u),ce=new RegExp('^(?:"('+Ut+`|\\\\[^\\\\]|[^\\\\"\\x00])*"|'(`+Ut+"|\\\\[^\\\\]|[^\\\\'\\x00])*'|\\(("+Ut+"|\\\\[^\\\\]|[^\\\\()\\x00])*\\))"),he=/^(?:<(?:[^<>\n\\\x00]|\\.)*>)/,
It=new RegExp("^"+Mt),ue=new RegExp("^"+le,"i"),pe=/`+/,fe=/^`+/,de=/\.\.\./g,_e=/--+/g,ge=/^<([a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*)>/,me=/^<[A-Za-z][A-Za-z0-9.+-]{1,31}:[^<>\x00-\x20]*>/i,ve=/^ *(?:\n *)?/,qt=/^[ \t\n\x0b\x0c\x0d]/,Gt=/^\s/,ke=/ *$/,be=/^ */,Qt=/^ *(?:\n|$)/,Ce=/^\[(?:[^\\\[\]]|\\.){0,1000}\]/s,
xe=/^\\\((?:(?!\\\))[\s\S])+\\\)/,ye=/^\\\[(?:(?!\\\])[\s\S])+\\\](?=[ \t]*(?:\n|$))/,Le=/^[^\n`\[\]\\!<&*_'"~]+/m,w=function(t){var e=new _("text");return e._literal=t,e},Xt=function(t){return t.slice(1,t.length-1).trim().replace(/[ \t\r\n]+/g," ").toLowerCase().toUpperCase()},Ne=function(t){var e=t.exec(this.subject.slice(this.pos));return e===null?null:(this.pos+=e.index+e[0].length,e[0])},we=function(){
return this.pos<this.subject.length?this.subject.charCodeAt(this.pos):-1},Oe=function(){return this.match(ve),!0},De=function(t){var e=this.match(fe);if(e===null)return!1;for(var n=this.pos,i,r,s;(i=this.match(pe))!==null;)if(i===e)return r=new _("code"),s=this.subject.slice(n,this.pos-e.length).replace(/\n/gm," "),s.length>0&&s.match(/[^ ]/)!==null&&s[0]==" "&&s[s.length-1]==" "?r._literal=s.slice(
1,s.length-1):r._literal=s,t.appendChild(r),!0;return this.pos=n,t.appendChild(w(e)),!0},Ae=function(t){var e=this.subject,n,i=e.charAt(this.pos+1),r=i==="("?this.match(xe):i==="["&&(this.pos===0||e.charAt(this.pos-1)===`
`)?this.match(ye):null;return r?(n=new _("math"),n._literal=r,t.appendChild(n),!0):(this.pos+=1,this.peek()===q?(this.pos+=1,n=new _("linebreak"),t.appendChild(n)):It.test(e.charAt(this.pos))?(t.appendChild(w(e.charAt(this.pos))),this.pos+=1):t.appendChild(w("\\")),!0)},Be=function(t){var e,n,i;return(e=this.match(ge))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=I("mailto:"+n),i._title=
"",i.appendChild(w(n)),t.appendChild(i),!0):(e=this.match(me))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=I(n),i._title="",i.appendChild(w(n)),t.appendChild(i),!0):!1},je=function(t){var e=this.match(oe);if(e===null)return!1;var n=new _("html_inline");return n._literal=e,t.appendChild(n),!0},Ee=function(t){var e=0,n,i,r,s=this.pos,l,a,o,u,d,L,x,y;if(t===V||t===tt)e++,this.pos++;else for(;this.
peek()===t;)e++,this.pos++;return e===0?null:(n=s===0?`
`:this.subject.charAt(s-1),r=this.peek(),r===-1?i=`
`:i=lt(r),d=Gt.test(i),L=Ht.test(i),x=Gt.test(n),y=Ht.test(n),l=!d&&(!L||x||y),a=!x&&(!y||d||L),t===g?(o=l&&(!a||y),u=a&&(!l||L)):t===V||t===tt?(o=l&&!a,u=a):(o=l,u=a),this.pos=s,{numdelims:e,can_open:o,can_close:u})},Pe=function(t,e){var n=this.scanDelims(t);if(!n)return!1;var i=n.numdelims,r=this.pos,s;this.pos+=i,t===V?s="\u2019":t===tt?s="\u201C":s=this.subject.slice(r,this.pos);var l=w(s);return e.
appendChild(l),(n.can_open||n.can_close)&&(this.options.smart||t!==V&&t!==tt)&&(this.delimiters={cc:t,numdelims:i,origdelims:i,node:l,previous:this.delimiters,next:null,can_open:n.can_open,can_close:n.can_close},this.delimiters.previous!==null&&(this.delimiters.previous.next=this.delimiters)),!0},ze=function(t){t.previous!==null&&(t.previous.next=t.next),t.next===null?this.delimiters=t.previous:t.
next.previous=t.previous},Wt=function(t,e){t.next!==e&&(t.next=e,e.previous=t)},$e=function(t){for(var e,n,i,r,s,l,a,o,u,d,L=[],x,y=!1,xt=0;xt<14;xt++)L[xt]=t;for(n=this.delimiters;n!==null&&n.previous!==t;)n=n.previous;for(;n!==null;){var yt=n.cc;if(!n.can_close)n=n.next;else{switch(e=n.previous,d=!1,yt){case V:x=0;break;case tt:x=1;break;case g:x=2+(n.can_open?3:0)+n.origdelims%3;break;case p:x=
8+(n.can_open?3:0)+n.origdelims%3;break;case Rt:x=14;break}for(;e!==null&&e!==t&&e!==L[x];){if(y=(n.can_open||e.can_close)&&n.origdelims%3!==0&&(e.origdelims+n.origdelims)%3===0,e.cc===n.cc&&e.can_open&&!y){d=!0;break}e=e.previous}if(i=n,yt===Rt)if(!d||n.numdelims<2||e.numdelims<2)n=n.next;else{r=e.node,s=n.node,e.numdelims-=2,n.numdelims-=2,r._literal=r._literal.slice(0,r._literal.length-2),s._literal=
s._literal.slice(0,s._literal.length-2);for(var Bn=new _("strikethrough"),At=r._next;At&&At!==s;){var Sn=At._next;Bn.appendChild(At),At=Sn}r.insertAfter(Bn),Wt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else if(yt===p||yt===g)if(!d)n=n.next;else{a=n.numdelims>=2&&e.numdelims>=2?2:1,r=e.node,s=n.node,e.numdelims-=a,n.
numdelims-=a,r._literal=r._literal.slice(0,r._literal.length-a),s._literal=s._literal.slice(0,s._literal.length-a);var jn=new _(a===1?"emph":"strong");for(o=r._next;o&&o!==s;)u=o._next,o.unlink(),jn.appendChild(o),o=u;r.insertAfter(jn),Wt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else yt===V?(n.node._literal="\u2019",
d&&(e.node._literal="\u2018"),n=n.next):yt===tt&&(n.node._literal="\u201D",d&&(e.node.literal="\u201C"),n=n.next);d||(L[x]=i.previous,i.can_open||this.removeDelimiter(i))}}for(;this.delimiters!==null&&this.delimiters!==t;)this.removeDelimiter(this.delimiters)},Se=function(){var t=this.match(ce);return t===null?null:P(t.slice(1,-1))},Te=function(){var t=this.match(he);if(t===null){if(this.peek()===
bt)return null;for(var e=this.pos,n=0,i;(i=this.peek())!==-1;)if(i===Ft&&It.test(this.subject.charAt(this.pos+1)))this.pos+=1,this.peek()!==-1&&(this.pos+=1);else if(i===Zt)this.pos+=1,n+=1;else if(i===Tt){if(n<1)break;this.pos+=1,n-=1}else{if(qt.exec(lt(i))!==null)break;this.pos+=1}return this.pos===e&&i!==Tt||n!==0?null:(t=this.subject.slice(e,this.pos),I(P(t)))}else return I(P(t.slice(1,-1)))},
Re=function(){var t=this.match(Ce);return t===null||t.length>1001?0:t.length},Ue=function(t){var e=this.pos,n=this.match(/^\[\^[^\]]+\]/);if(n){var i=new _("footnote_reference");return i._label=n.slice(2,-1),t.appendChild(i),!0}this.pos+=1;var r=w("[");return t.appendChild(r),this.addBracket(r,e,!1),!0},Fe=function(t){var e=this.pos;if(this.pos+=1,this.peek()===Y){this.pos+=1;var n=w("![");t.appendChild(
n),this.addBracket(n,e+1,!0)}else t.appendChild(w("!"));return!0},Ze=function(t){var e,n,i,r,s=!1,l,a;if(this.pos+=1,e=this.pos,a=this.brackets,a===null)return t.appendChild(w("]")),!0;if(!a.active)return t.appendChild(w("]")),this.removeBracket(),!0;n=a.image;var o=this.pos;if(this.peek()===Zt&&(this.pos++,this.spnl()&&(i=this.parseLinkDestination())!==null&&this.spnl()&&(qt.test(this.subject.charAt(
this.pos-1))&&(r=this.parseLinkTitle())||!0)&&this.spnl()&&this.peek()===Tt?(this.pos+=1,s=!0):this.pos=o),!s){var u=this.pos,d=this.parseLinkLabel();if(d>2?l=this.subject.slice(u,u+d):a.bracketAfter||(l=this.subject.slice(a.index,e)),d===0&&(this.pos=o),l){var L=this.refmap[Xt(l)];L&&(i=L.destination,r=L.title,s=!0)}}if(s){var x=new _(n?"image":"link");x._destination=i,x._title=r||"";var y,xt;for(y=
a.node._next;y;)xt=y._next,y.unlink(),x.appendChild(y),y=xt;if(t.appendChild(x),this.processEmphasis(a.previousDelimiter),this.removeBracket(),a.node.unlink(),!n)for(a=this.brackets;a!==null;)a.image||(a.active=!1),a=a.previous;return!0}else return this.removeBracket(),this.pos=e,t.appendChild(w("]")),!0},Me=function(t,e,n){this.brackets!==null&&(this.brackets.bracketAfter=!0),this.brackets={node:t,
previous:this.brackets,previousDelimiter:this.delimiters,index:e,image:n,active:!0}},He=function(){this.brackets=this.brackets.previous},Ie=function(t){var e;return(e=this.match(ue))?(t.appendChild(w((0,T.decodeHTMLStrict)(e))),!0):!1},qe=function(t){var e;return(e=this.match(Le))?(this.options.smart?t.appendChild(w(e.replace(de,"\u2026").replace(_e,function(n){var i=0,r=0;return n.length%3===0?r=
n.length/3:n.length%2===0?i=n.length/2:n.length%3===2?(i=1,r=(n.length-2)/3):(i=2,r=(n.length-4)/3),"\u2014".repeat(r)+"\u2013".repeat(i)}))):t.appendChild(w(e)),!0):!1},Ge=function(t){this.pos+=1;var e=t._lastChild;if(e&&e.type==="text"&&e._literal[e._literal.length-1]===" "){var n=e._literal[e._literal.length-2]===" ";e._literal=e._literal.replace(ke,""),t.appendChild(new _(n?"linebreak":"softbr\
eak"))}else t.appendChild(new _("softbreak"));return this.match(be),!0},Qe=function(t,e){this.subject=t,this.pos=0;var n,i,r,s,l=this.pos;if(s=this.parseLinkLabel(),s===0)return 0;if(n=this.subject.slice(0,s),this.peek()===ae)this.pos++;else return this.pos=l,0;if(this.spnl(),i=this.parseLinkDestination(),i===null)return this.pos=l,0;var a=this.pos;this.spnl(),this.pos!==a&&(r=this.parseLinkTitle()),
r===null&&(this.pos=a);var o=!0;if(this.match(Qt)===null&&(r===null?o=!1:(r=null,this.pos=a,o=this.match(Qt)!==null)),!o)return this.pos=l,0;var u=Xt(n);return u===""?(this.pos=l,0):(e[u]||(e[u]={destination:i,title:r===null?"":r}),this.pos-l)},Xe=function(t){var e=!1,n=this.peek();if(n===-1)return!1;switch(n){case q:e=this.parseNewline(t);break;case Ft:e=this.parseBackslash(t);break;case R:e=this.
parseBackticks(t);break;case p:case g:case Rt:e=this.handleDelim(n,t);break;case V:case tt:e=this.options.smart&&this.handleDelim(n,t);break;case Y:e=this.parseOpenBracket(t);break;case re:e=this.parseBang(t);break;case St:e=this.parseCloseBracket(t);break;case bt:e=this.parseAutolink(t)||this.parseHtmlTag(t);break;case se:e=this.parseEntity(t);break;default:e=this.parseString(t);break}return e||(this.
pos+=1,t.appendChild(w(lt(n)))),!0},We=function(t){for(this.subject=t._string_content.trim(),this.pos=0,this.delimiters=null,this.brackets=null;this.parseInline(t););t._string_content=null,this.processEmphasis(null)},Je=$t}),Ke={};Lt(Ke,{default:()=>An});function Pn(t){return{doc:new ie,blocks:ne,blockStarts:Cn,tip:this.doc,oldtip:this.doc,currentLine:"",lineNumber:0,offset:0,column:0,nextNonspace:0,
nextNonspaceColumn:0,indent:0,indented:!1,blank:!1,partiallyConsumedTab:!1,allClosed:!0,lastMatchedContainer:this.doc,refmap:{},lastLineLength:0,inlineParser:new Je(t),findNextNonspace:Ln,advanceOffset:xn,advanceNextNonspace:yn,addLine:_n,addChild:gn,incorporateLine:Nn,finalize:wn,processInlines:On,closeUnmatchedBlocks:kn,parse:Dn,options:t||{}}}var Ot,Jt,Ye,Kt,Ve,Yt,Vt,tn,en,nn,rn,sn,Dt,an,te,ln,
on,cn,hn,un,pn,fn,dn,Ct,B,ee,_n,gn,mn,vn,kn,bn,ne,Cn,xn,yn,Ln,Nn,wn,On,ie,Dn,An,zn=z(()=>{"use strict";Nt(),J(),En(),Ot=4,Jt=9,Ye=10,Kt=62,Ve=60,Yt=32,Vt=91,tn=[/./,/^<(?:script|pre|textarea|style)(?:\s|>|$)/i,/^<!--/,/^<[?]/,/^<![A-Za-z]/,/^<!\[CDATA\[/,/^<[/]?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[123456]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|nav|noframes|ol|optgroup|option|p|param|section|search|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?:\s|[/]?[>]|$)/i,
new RegExp("^(?:"+st+"|"+h+")\\s*$","i")],en=[/./,/<\/(?:script|pre|textarea|style)>/i,/-->/,/\?>/,/>/,/\]\]>/],nn=/^(?:\*[ \t]*){3,}$|^(?:_[ \t]*){3,}$|^(?:-[ \t]*){3,}$/,rn=/^\[\^([^\]]+)\]:[ \t]*/,sn=/^\|?[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)*\|?[ \t]*$/,Dt=function(t){var e=[],n="",i,r;for(t=t.trim().replace(/^\|/,"").replace(/\|[ \t]*$/,""),i=0;i<t.length;i++)r=t.charAt(i),r==="\\"&&t.charAt(
i+1)==="|"?(n+="|",i++):r==="|"?(e.push(n.trim()),n=""):n+=r;return e.push(n.trim()),e},an=/^[#`~*+_=<>0-9|:[-]/,te=/[^ \t\f\v\r\n]/,ln=/^[*+-]/,on=/^(\d{1,9})([.)])/,cn=/^#{1,6}(?:[ \t]+|$)/,hn=/^`{3,}(?!.*`)|^~{3,}/,un=/^(?:`{3,}|~{3,})(?=[ \t]*$)/,pn=/^(?:=+|-+)[ \t]*$/,fn=/\r\n|\n|\r/,dn=function(t){return!te.test(t)},Ct=function(t){return t===Yt||t===Jt},B=function(t,e){return e<t.length?t.charCodeAt(
e):-1},ee=function(t){return t.next&&t.sourcepos[1][0]!==t.next.sourcepos[0][0]-1},_n=function(){if(this.partiallyConsumedTab){this.offset+=1;var t=4-this.column%4;this.tip._string_content+=" ".repeat(t)}this.tip._string_content+=this.currentLine.slice(this.offset)+`
`},gn=function(t,e){for(;!this.blocks[this.tip.type].canContain(t);)this.finalize(this.tip,this.lineNumber-1);var n=e+1,i=new _(t,[[this.lineNumber,n],[0,0]]);return i._string_content="",this.tip.appendChild(i),this.tip=i,i},mn=function(t,e){var n=t.currentLine.slice(t.nextNonspace),i,r,s,l,a={type:null,tight:!0,bulletChar:null,start:null,delimiter:null,padding:null,markerOffset:t.indent};if(t.indent>=
4)return null;if(i=n.match(ln))a.type="bullet",a.bulletChar=i[0][0];else if((i=n.match(on))&&(e.type!=="paragraph"||i[1]==1))a.type="ordered",a.start=parseInt(i[1]),a.delimiter=i[2];else return null;if(r=B(t.currentLine,t.nextNonspace+i[0].length),!(r===-1||r===Jt||r===Yt)||e.type==="paragraph"&&!t.currentLine.slice(t.nextNonspace+i[0].length).match(te))return null;t.advanceNextNonspace(),t.advanceOffset(
i[0].length,!0),s=t.column,l=t.offset;do t.advanceOffset(1,!0),r=B(t.currentLine,t.offset);while(t.column-s<5&&Ct(r));var o=B(t.currentLine,t.offset)===-1,u=t.column-s;return u>=5||u<1||o?(a.padding=i[0].length+1,t.column=s,t.offset=l,Ct(B(t.currentLine,t.offset))&&t.advanceOffset(1,!0)):a.padding=i[0].length+u,a},vn=function(t,e){return t.type===e.type&&t.delimiter===e.delimiter&&t.bulletChar===e.
bulletChar},kn=function(){if(!this.allClosed){for(;this.oldtip!==this.lastMatchedContainer;){var t=this.oldtip._parent;this.finalize(this.oldtip,this.lineNumber-1),this.oldtip=t}this.allClosed=!0}},bn=function(t,e){for(var n,i,r=e.walker(),s=[];n=r.next();)if(i=n.node,n.entering&&i.type==="paragraph"){for(var l,a=!1;B(i._string_content,0)===Vt&&(l=t.inlineParser.parseReference(i._string_content,t.
refmap));){let o=i._string_content.slice(0,l);i._string_content=i._string_content.slice(l),a=!0;let u=o.split(`
`);i.sourcepos[0][0]+=u.length-1}a&&dn(i._string_content)&&s.push(i)}for(i of s)i.unlink()},ne={document:{continue:function(){return 0},finalize:function(t,e){bn(t,e)},canContain:function(t){return t!=="item"},acceptsLines:!1},list:{continue:function(){return 0},finalize:function(t,e){for(var n=e._firstChild;n;){if(n._next&&ee(n)){e._listData.tight=!1;break}for(var i=n._firstChild;i;){if(i._next&&
ee(i)){e._listData.tight=!1;break}i=i._next}n=n._next}e.sourcepos[1]=e._lastChild.sourcepos[1]},canContain:function(t){return t==="item"},acceptsLines:!1},block_quote:{continue:function(t){var e=t.currentLine;if(!t.indented&&B(e,t.nextNonspace)===Kt)t.advanceNextNonspace(),t.advanceOffset(1,!1),Ct(B(e,t.offset))&&t.advanceOffset(1,!0);else return 1;return 0},finalize:function(){},canContain:function(t){
return t!=="item"},acceptsLines:!1},item:{continue:function(t,e){if(t.blank){if(e._firstChild==null)return 1;t.advanceNextNonspace()}else if(t.indent>=e._listData.markerOffset+e._listData.padding)t.advanceOffset(e._listData.markerOffset+e._listData.padding,!0);else return 1;return 0},finalize:function(t,e){e._lastChild?e.sourcepos[1]=e._lastChild.sourcepos[1]:(e.sourcepos[1][0]=e.sourcepos[0][0],e.
sourcepos[1][1]=e._listData.markerOffset+e._listData.padding)},canContain:function(t){return t!=="item"},acceptsLines:!1},heading:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},thematic_break:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},code_block:{continue:function(t,e){var n=t.currentLine,
i=t.indent;if(e._isFenced){var r=i<=3&&n.charAt(t.nextNonspace)===e._fenceChar&&n.slice(t.nextNonspace).match(un);if(r&&r[0].length>=e._fenceLength)return t.lastLineLength=t.offset+i+r[0].length,t.finalize(e,t.lineNumber),2;for(var s=e._fenceOffset;s>0&&Ct(B(n,t.offset));)t.advanceOffset(1,!0),s--}else if(i>=Ot)t.advanceOffset(Ot,!0);else if(t.blank)t.advanceNextNonspace();else return 1;return 0},
finalize:function(t,e){if(e._isFenced){var n=e._string_content,i=n.indexOf(`
`),r=n.slice(0,i),s=n.slice(i+1);e.info=kt(r.trim()),e._literal=s}else{for(var l=e._string_content.split(`
`);/^[ \t]*$/.test(l[l.length-1]);)l.pop();e._literal=l.join(`
`)+`
`,e.sourcepos[1][0]=e.sourcepos[0][0]+l.length-1,e.sourcepos[1][1]=e.sourcepos[0][1]+l[l.length-1].length-1}e._string_content=null},canContain:function(){return!1},acceptsLines:!0},html_block:{continue:function(t,e){return t.blank&&(e._htmlBlockType===6||e._htmlBlockType===7)?1:0},finalize:function(t,e){e._literal=e._string_content.replace(/\n$/,""),e._string_content=null},canContain:function(){return!1},
acceptsLines:!0},footnote_definition:{continue:function(t){return t.blank?0:t.indent>=4?(t.advanceOffset(4,!0),0):t.tip.type==="paragraph"?0:1},finalize:function(){},canContain:function(t){return t!=="item"&&t!=="footnote_definition"},acceptsLines:!1},table:{continue:function(t){return t.blank?1:0},finalize:function(t,e){var n=e._string_content.replace(/\n$/,"").split(`
`),i=Dt(n[1]),r=i.map(function(d){var L=d.charAt(0)===":",x=d.charAt(d.length-1)===":";return L&&x?"center":x?"right":L?"left":null}),s,l,a,o,u;for(s=0;s<n.length;s++)if(s!==1){for(a=Dt(n[s]),o=new _("table_row"),o._isHeading=s===0,l=0;l<i.length;l++)u=new _("table_cell"),u._align=r[l],u._string_content=a[l]===void 0?"":a[l],o.appendChild(u);e.appendChild(o)}e._string_content=null},canContain:function(t){
return t==="table_row"},acceptsLines:!0},paragraph:{continue:function(t){return t.blank?1:0},finalize:function(){},canContain:function(){return!1},acceptsLines:!0}},Cn=[function(t){if(t.indented)return 0;var e=t.currentLine.slice(t.nextNonspace).match(rn);if(!e)return 0;t.closeUnmatchedBlocks(),t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1);var n=t.addChild("footnote_definition",t.nextNonspace);
return n._label=e[1],1},function(t,e){if(t.indented||e.type!=="paragraph")return 0;var n=t.currentLine.slice(t.nextNonspace);if(n.indexOf("|")===-1||!sn.test(n))return 0;var i=e._string_content.replace(/\n$/,"").split(`
`),r=i[i.length-1];if(!r||r.indexOf("|")===-1||Dt(r).length!==Dt(n).length)return 0;var s=i.slice(0,i.length-1).join(`
`);e._string_content=s===""?"":s+`
`,t.closeUnmatchedBlocks();var l=s==="",a=t.addChild("table",t.nextNonspace);return l&&e.unlink(),a._string_content=r+`
`,2},function(t){return!t.indented&&B(t.currentLine,t.nextNonspace)===Kt?(t.advanceNextNonspace(),t.advanceOffset(1,!1),Ct(B(t.currentLine,t.offset))&&t.advanceOffset(1,!0),t.closeUnmatchedBlocks(),t.addChild("block_quote",t.nextNonspace),1):0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(cn))){t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1),t.closeUnmatchedBlocks();
var n=t.addChild("heading",t.nextNonspace);return n.level=e[0].trim().length,n._string_content=t.currentLine.slice(t.offset).replace(/^[ \t]*#+[ \t]*$/,"").replace(/[ \t]+#+[ \t]*$/,""),t.advanceOffset(t.currentLine.length-t.offset),2}else return 0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(hn))){var n=e[0].length;t.closeUnmatchedBlocks();var i=t.addChild("code\
_block",t.nextNonspace);return i._isFenced=!0,i._fenceLength=n,i._fenceChar=e[0][0],i._fenceOffset=t.indent,t.advanceNextNonspace(),t.advanceOffset(n,!1),2}else return 0},function(t,e){if(!t.indented&&B(t.currentLine,t.nextNonspace)===Ve){var n=t.currentLine.slice(t.nextNonspace),i;for(i=1;i<=7;i++)if(tn[i].test(n)&&(i<7||e.type!=="paragraph"&&!(!t.allClosed&&!t.blank&&t.tip.type==="paragraph"))){
t.closeUnmatchedBlocks();var r=t.addChild("html_block",t.offset);return r._htmlBlockType=i,2}}return 0},function(t,e){var n;if(!t.indented&&e.type==="paragraph"&&(n=t.currentLine.slice(t.nextNonspace).match(pn))){t.closeUnmatchedBlocks();for(var i;B(e._string_content,0)===Vt&&(i=t.inlineParser.parseReference(e._string_content,t.refmap));)e._string_content=e._string_content.slice(i);if(e._string_content.
length>0){var r=new _("heading",e.sourcepos);return r.level=n[0][0]==="="?1:2,r._string_content=e._string_content,e.insertAfter(r),e.unlink(),t.tip=r,t.advanceOffset(t.currentLine.length-t.offset,!1),2}else return 0}else return 0},function(t){return!t.indented&&nn.test(t.currentLine.slice(t.nextNonspace))?(t.closeUnmatchedBlocks(),t.addChild("thematic_break",t.nextNonspace),t.advanceOffset(t.currentLine.
length-t.offset,!1),2):0},function(t,e){var n;return(!t.indented||e.type==="list")&&(n=mn(t,e))?(t.closeUnmatchedBlocks(),(t.tip.type!=="list"||!vn(e._listData,n))&&(e=t.addChild("list",t.nextNonspace),e._listData=n),e=t.addChild("item",t.nextNonspace),e._listData=n,1):0},function(t){return t.indented&&t.tip.type!=="paragraph"&&!t.blank?(t.advanceOffset(Ot,!0),t.closeUnmatchedBlocks(),t.addChild("\
code_block",t.offset),2):0}],xn=function(t,e){for(var n=this.currentLine,i,r,s;t>0&&(s=n[this.offset]);)s==="	"?(i=4-this.column%4,e?(this.partiallyConsumedTab=i>t,r=i>t?t:i,this.column+=r,this.offset+=this.partiallyConsumedTab?0:1,t-=r):(this.partiallyConsumedTab=!1,this.column+=i,this.offset+=1,t-=1)):(this.partiallyConsumedTab=!1,this.offset+=1,this.column+=1,t-=1)},yn=function(){this.offset=this.
nextNonspace,this.column=this.nextNonspaceColumn,this.partiallyConsumedTab=!1},Ln=function(){for(var t=this.currentLine,e=this.offset,n=this.column,i;(i=t.charAt(e))!=="";)if(i===" ")e++,n++;else if(i==="	")e++,n+=4-n%4;else break;this.blank=i===`
`||i==="\r"||i==="",this.nextNonspace=e,this.nextNonspaceColumn=n,this.indent=this.nextNonspaceColumn-this.column,this.indented=this.indent>=Ot},Nn=function(t){var e=!0,n,i=this.doc;this.oldtip=this.tip,this.offset=0,this.column=0,this.blank=!1,this.partiallyConsumedTab=!1,this.lineNumber+=1,t.indexOf("\0")!==-1&&(t=t.replace(/\0/g,"\uFFFD")),this.currentLine=t;for(var r;(r=i._lastChild)&&r._open;){
switch(i=r,this.findNextNonspace(),this.blocks[i.type].continue(this,i)){case 0:break;case 1:e=!1;break;case 2:return;default:throw"continue returned illegal value, must be 0, 1, or 2"}if(!e){i=i._parent;break}}this.allClosed=i===this.oldtip,this.lastMatchedContainer=i;for(var s=i.type!=="paragraph"&&i.type!=="table"&&ne[i.type].acceptsLines,l=this.blockStarts,a=l.length;!s;){if(this.findNextNonspace(),
!this.indented&&!an.test(t.slice(this.nextNonspace))){this.advanceNextNonspace();break}for(var o=0;o<a;){var u=l[o](this,i);if(u===1){i=this.tip;break}else if(u===2){i=this.tip,s=!0;break}else o++}if(o===a){this.advanceNextNonspace();break}}!this.allClosed&&!this.blank&&this.tip.type==="paragraph"?this.addLine():(this.closeUnmatchedBlocks(),n=i.type,this.blocks[n].acceptsLines?(this.addLine(),n===
"html_block"&&i._htmlBlockType>=1&&i._htmlBlockType<=5&&en[i._htmlBlockType].test(this.currentLine.slice(this.offset))&&(this.lastLineLength=t.length,this.finalize(i,this.lineNumber))):this.offset<t.length&&!this.blank&&(i=this.addChild("paragraph",this.offset),this.advanceNextNonspace(),this.addLine())),this.lastLineLength=t.length},wn=function(t,e){var n=t._parent;t._open=!1,t.sourcepos[1]=[e,this.
lastLineLength],this.blocks[t.type].finalize(this,t),this.tip=n},On=function(t){var e,n,i,r=t.walker();for(this.inlineParser.refmap=this.refmap,this.inlineParser.options=this.options;n=r.next();)e=n.node,i=e.type,!n.entering&&(i==="paragraph"||i==="heading"||i==="table_cell")&&this.inlineParser.parse(e)},ie=function(){var t=new _("document",[[1,1],[0,0]]);return t},Dn=function(t){this.doc=new ie,this.
tip=this.doc,this.refmap={},this.lineNumber=0,this.lastLineLength=0,this.offset=0,this.column=0,this.lastMatchedContainer=this.doc,this.currentLine="",this.options.time&&console.time("preparing input");var e=t.split(fn),n=e.length;t.charCodeAt(t.length-1)===Ye&&(n-=1),this.options.time&&console.timeEnd("preparing input"),this.options.time&&console.time("block parsing");for(var i=0;i<n;i++)this.incorporateLine(
e[i]);for(;this.tip;)this.finalize(this.tip,n);return this.options.time&&console.timeEnd("block parsing"),this.options.time&&console.time("inline parsing"),this.processInlines(this.doc),this.options.time&&console.timeEnd("inline parsing"),this.doc},An=Pn}),$n=F((t,e)=>{var n=(zn(),v(Ke));e.exports={Parser:n.Parser||n.default||n}});return $n()})();function protectBlockBody(f){return f.split(`
`).map(function(m){return m.replace(/^([ \t]*)(,*)(\*|#\+)/,"$1$2,$3")}).join(`
`)}function codeSpan(f){return f.indexOf("=")===-1?"="+f+"=":f.indexOf("~")===-1?"~"+f+"~":f}function escapeCell(f){return String(f).replace(/\|/g,"\\|")}function linkType(f){return/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(f)||/^[/~#]/.test(f)||/^\.\.?\//.test(f)}function escapeLinkPath(f){var m=String(f);return m&&!linkType(m)&&(m="file:"+m),m.replace(/([\[\]\\])/g,"\\$1")}function fnLabel(f){return String(
f).trim().toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"")||"fn"}function renderOrg(f,m){for(var G={},et={},ot=f.walker(),U,z,F,Lt;U=ot.next();)if(!(!U.entering||U.node.type!=="footnote_definition")&&(z=U.node._label,G[z]===void 0)){for(F=fnLabel(z),Lt=1;et[F];)Lt++,F=fnLabel(z)+"-"+Lt;et[F]=1,G[z]=F}function ct(p){return G[p]!==void 0?G[p]:null}renderOrg.warn||(renderOrg.warn={});
var N=[],v="",ht=[],$=[],Q=0,ut=0,D=0,k=0,_=!0,Nt=!1,pt=0,nt=!1,Z=!1,ft=0,dt=0,X=0,M=!1,it="",_t=!1,gt=!1,mt=!1,rt=-1;function H(p){var g=renderOrg.warn[p]||(renderOrg.warn[p]=[]),R=N.length+1;g[g.length-1]!==R&&g.push(R)}function C(){return ht.join("")}function st(p,g,R){return p!==g&&H(R),g}function h(p){p&&(v+=p,_=!1)}function b(){$.length&&(v=v.replace(/^(\s*(?:-|\d+\.) )\[x\] /,"$1[X] ")),!_t&&
/^\*+\s/.test(v)&&H("heading"),!gt&&!mt&&/^[ \t]*#(\s|$)/.test(v)&&H("comment"),M&&/^[ \t]*#\+(BEGIN|END)_/i.test(v)&&H("stray block delimiter"),/\[\[[^\]]*\]\]/.test(it)&&H("[[ ]] read as an Org link"),M=!1,it="",_t=!1,gt=!1,N.push(v),v="",_=!0}function j(){v!==""&&b()}function at(){N.length&&N[N.length-1]!==""&&N.push("")}function A(p){var g=p.sourcepos;if(!g){at();return}pt&&g[0][0]>pt+1&&at()}
function E(p){p.sourcepos&&(pt=p.sourcepos[1][0])}function Bt(p){var g=nt?st(p,m.escapeCell(p),"\\| in a table cell"):p;M=!0,it+=g,h(g)}function jt(){var p=rt>=0?v.slice(rt):"";(p.indexOf("]]")!==-1||p.slice(-1)==="]")&&H("]] in a link description"),rt=-1,h("]]")}function vt(p){mt=!0,p.replace(/\n$/,"").split(`
`).forEach(function(g){h(C()+g),b()}),mt=!1}function Et(p){var g=p.replace(/\n$/,""),R=/^ {0,3}<!--/.exec(g);if(!R)return!1;var Y=g.indexOf("-->");if(Y!==-1&&!/^\s*$/.test(g.slice(Y+3)))return!1;var St=g.slice(R[0].length,Y===-1?void 0:Y);return St.split(`
`).forEach(function(bt){h(C()+(bt?"# "+bt:"#")),gt=!0,b()}),!0}for(var Pt=f.walker(),O,c,kt;O=Pt.next();)switch(c=O.node,kt=c.type,kt){case"text":ut===0&&Bt(c.literal,c);break;case"softbreak":if(Z){h(" ");break}if(X){h(" ");break}b(),h(C()),_=!0;break;case"linebreak":h("\\\\"),b(),h(C()),_=!0;break;case"code":var W=c.literal,J,lt;nt&&W.indexOf("|")!==-1?(J=st(W,m.escapeCell(W),"\\| in a table cell"),
lt=!0):(J=m.codeSpan(W),lt=J===W),M=!0,lt&&(it+=J),h(J);break;case"math":var K=c.literal.split(`
`),S;for(M=!0,S=0;S<K.length;S++)S&&(Z||X?h(" "):(b(),h(C()))),h(nt?st(K[S],m.escapeCell(K[S]),"\\| in a table cell"):K[S]);break;case"emph":h("/");break;case"footnote_definition":O.entering?(j(),c.prev&&c.prev.type==="footnote_definition"?at():A(c),h(C()+"[fn:"+ct(c._label)+"] "),Z=!0):(Z=!1,v=v.replace(/[ \t]+$/,""),b(),at(),E(c));break;case"footnote_reference":h(ct(c._label)?"[fn:"+ct(c._label)+
"]":"[^"+c._label+"]");break;case"table":O.entering?(j(),A(c)):E(c);break;case"table_row":if(O.entering)h(C()+"|");else if(b(),c._isHeading){for(var wt=[],zt=[],$t=!1,T=c.firstChild;T;)wt.push("----"),zt.push(T._align==="center"?" <c> ":T._align==="right"?" <r> ":T._align==="left"?" <l> ":" "),T._align&&($t=!0),T=T.next;h(C()+"|"+wt.join("+")+"|"),b(),$t&&(h(C()+"|"+zt.join("|")+"|"),b())}break;case"\
table_cell":nt=O.entering,O.entering?h(" "):h(" |");break;case"strikethrough":h("+");break;case"strong":h("*");break;case"link":case"image":O.entering?(Q>0?(h(m.escapeLinkPath(c.destination)),ut++):c.destination&&!c.firstChild?(h("[["+m.escapeLinkPath(c.destination)),k++):!c.destination||c.destination[0]==="#"?D++:(h("[["+m.escapeLinkPath(c.destination)+"]["),Q===0&&(rt=v.length)),Q++):(Q--,Q>0?ut--:
D?D--:k?(k--,h("]]")):jt());break;case"html_inline":h("@@html:"+c.literal+"@@");break;case"html_block":j(),A(c),Et(c.literal)||(h(C()+"#+BEGIN_EXPORT html"),b(),vt(m.protectBlockBody(c.literal)),h(C()+"#+END_EXPORT"),b()),E(c);break;case"paragraph":O.entering?(Z||A(c),v===""&&(v+=C()),_=!0,Nt=!0):(Z?h(" "):b(),Nt=!1,E(c));break;case"heading":O.entering?(X++,dt=ft||$.length,dt?($.length||A(c),v===""&&
(v+=C()),h("*")):(j(),A(c),h("*".repeat(c.level)+" "),_t=!0)):(dt&&(v.slice(-1)==="*"?v=v.slice(0,-1):h("*")),X--,b(),E(c));break;case"code_block":j(),A(c);var I=(c.info||"").trim().split(/[\s{}]+/).filter(Boolean)[0]||"";h(C()+(I?"#+BEGIN_SRC "+I:"#+BEGIN_EXAMPLE")),b(),vt(m.protectBlockBody(c.literal)),h(C()+(I?"#+END_SRC":"#+END_EXAMPLE")),b(),E(c);break;case"thematic_break":j(),A(c),h(C()+"---\
--"),b(),E(c);break;case"block_quote":O.entering?(j(),A(c),h(C()+"#+BEGIN_QUOTE"),b(),ft++,c.sourcepos&&(pt=c.sourcepos[0][0])):(ft--,j(),h(C()+"#+END_QUOTE"),b(),E(c));break;case"list":O.entering?($.length||A(c),$.push({ordered:c.listType==="ordered",n:c.listStart===null||c.listStart===void 0?1:c.listStart,first:!0})):($.pop(),E(c));break;case"item":if(O.entering){j();var P=$[$.length-1],q;P.ordered?
(q=P.n+". ",P.first&&P.n!==1&&(q+="[@"+P.n+"] "),P.n++):q="- ",P.first=!1,v+=C()+q,ht.push(" ".repeat(q.length)),_=!0}else ht.pop();break;default:break}for(v!==""&&b();N.length&&N[0]==="";)N.shift();for(;N.length&&N[N.length-1]==="";)N.pop();return N.join(`
`)}function md2org(f){if(typeof f!="string"&&(f=String(f??"")),f==="")return"";renderOrg.warn={};var m=new __cmark.Parser({sourcepos:!0}),G={codeSpan,escapeLinkPath,protectBlockBody,escapeCell},et=renderOrg(m.parse(f),G),ot=Object.keys(renderOrg.warn);return ot.length?et+`

# md2org warnings:
`+ot.map(function(U){return"# "+U+": line "+renderOrg.warn[U].join(", ")}).join(`
`):et}

try{var i=$text==null?"":String($text);if(i=="")return "⚠️ md2org: no input — set the Text field to Clipboard";var o=md2org(i);return o==""?"⚠️ md2org: result was empty":o}catch(e){return "⚠️ md2org: "+(e&&e.message||e)}
