// md2org — Actions "Transform Text with JavaScript": input is $text, result is
// returned. Generated from src/ by build.js. Errors are prefixed "⚠️ md2org:".
var __cmark=(()=>{var f=Object.create,b=Object.defineProperty,B=Object.getOwnPropertyDescriptor,q=Object.getOwnPropertyNames,K=Object.getPrototypeOf,W=Object.prototype.hasOwnProperty,z=(t,e,n)=>()=>{if(n)throw n[0];try{return t&&(e=t(t=0)),e}catch(i){throw n=[i],i}},F=(t,e)=>()=>{try{return e||t((e={exports:{}}).exports,e),e.exports}catch(n){throw e=0,n}},ht=(t,e)=>{for(var n in e)b(t,n,{get:e[n],
enumerable:!0})},J=(t,e,n,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of q(e))!W.call(t,r)&&r!==n&&b(t,r,{get:()=>e[r],enumerable:!(i=B(e,r))||i.enumerable});return t},L=(t,e,n)=>(n=t!=null?f(K(t)):{},J(e||!t||!t.__esModule?b(n,"default",{value:t,enumerable:!0}):n,t)),v=t=>J(b({},"__esModule",{value:!0}),t);function Q(t){switch(t._type){case"document":case"block_quote":case"list":case"\
item":case"paragraph":case"heading":case"emph":case"strong":case"strikethrough":case"table":case"table_row":case"table_cell":case"footnote_definition":case"link":case"image":case"custom_inline":case"custom_block":return!0;default:return!1}}var S,R,Y,D,m,_,V=z(()=>{"use strict";S=function(t,e){this.current=t,this.entering=e===!0},R=function(){var t=this.current,e=this.entering;if(t===null)return null;
var n=Q(t);return e&&n?t._firstChild?(this.current=t._firstChild,this.entering=!0):this.entering=!1:t===this.root?this.current=null:t._next===null?(this.current=t._parent,this.entering=!1):(this.current=t._next,this.entering=!0),{entering:e,node:t}},Y=function(t){return{current:t,root:t,entering:!0,next:R,resumeAt:S}},D=function(t,e){this._type=t,this._parent=null,this._firstChild=null,this._lastChild=
null,this._prev=null,this._next=null,this._sourcepos=e,this._open=!0,this._string_content=null,this._literal=null,this._listData={},this._info=null,this._destination=null,this._title=null,this._isFenced=!1,this._fenceChar=null,this._fenceLength=0,this._fenceOffset=null,this._level=null,this._onEnter=null,this._onExit=null},m=D.prototype,Object.defineProperty(m,"isContainer",{get:function(){return Q(
this)}}),Object.defineProperty(m,"type",{get:function(){return this._type}}),Object.defineProperty(m,"firstChild",{get:function(){return this._firstChild}}),Object.defineProperty(m,"lastChild",{get:function(){return this._lastChild}}),Object.defineProperty(m,"next",{get:function(){return this._next}}),Object.defineProperty(m,"prev",{get:function(){return this._prev}}),Object.defineProperty(m,"pare\
nt",{get:function(){return this._parent}}),Object.defineProperty(m,"sourcepos",{get:function(){return this._sourcepos}}),Object.defineProperty(m,"literal",{get:function(){return this._literal},set:function(t){this._literal=t}}),Object.defineProperty(m,"destination",{get:function(){return this._destination},set:function(t){this._destination=t}}),Object.defineProperty(m,"title",{get:function(){return this.
_title},set:function(t){this._title=t}}),Object.defineProperty(m,"info",{get:function(){return this._info},set:function(t){this._info=t}}),Object.defineProperty(m,"level",{get:function(){return this._level},set:function(t){this._level=t}}),Object.defineProperty(m,"listType",{get:function(){return this._listData.type},set:function(t){this._listData.type=t}}),Object.defineProperty(m,"listTight",{get:function(){
return this._listData.tight},set:function(t){this._listData.tight=t}}),Object.defineProperty(m,"listStart",{get:function(){return this._listData.start},set:function(t){this._listData.start=t}}),Object.defineProperty(m,"listDelimiter",{get:function(){return this._listData.delimiter},set:function(t){this._listData.delimiter=t}}),Object.defineProperty(m,"onEnter",{get:function(){return this._onEnter},
set:function(t){this._onEnter=t}}),Object.defineProperty(m,"onExit",{get:function(){return this._onExit},set:function(t){this._onExit=t}}),D.prototype.appendChild=function(t){t.unlink(),t._parent=this,this._lastChild?(this._lastChild._next=t,t._prev=this._lastChild,this._lastChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.prependChild=function(t){t.unlink(),t._parent=this,this._firstChild?
(this._firstChild._prev=t,t._next=this._firstChild,this._firstChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.unlink=function(){this._prev?this._prev._next=this._next:this._parent&&(this._parent._firstChild=this._next),this._next?this._next._prev=this._prev:this._parent&&(this._parent._lastChild=this._prev),this._parent=null,this._next=null,this._prev=null},D.prototype.insertAfter=function(t){
t.unlink(),t._next=this._next,t._next&&(t._next._prev=t),t._prev=this,this._next=t,t._parent=this._parent,t._next||(t._parent._lastChild=t)},D.prototype.insertBefore=function(t){t.unlink(),t._prev=this._prev,t._prev&&(t._prev._next=t),t._next=this,this._prev=t,t._parent=this._parent,t._prev||(t._parent._firstChild=t)},D.prototype.walker=function(){var t=new Y(this);return t},_=D}),tt=F((t,e)=>{"us\
e strict";var n={};function i(s){var l,a,o=n[s];if(o)return o;for(o=n[s]=[],l=0;l<128;l++)a=String.fromCharCode(l),/^[0-9a-z]$/i.test(a)?o.push(a):o.push("%"+("0"+l.toString(16).toUpperCase()).slice(-2));for(l=0;l<s.length;l++)o[s.charCodeAt(l)]=s[l];return o}function r(s,l,a){var o,u,p,y,k,x="";for(typeof l!="string"&&(a=l,l=r.defaultChars),typeof a>"u"&&(a=!0),k=i(l),o=0,u=s.length;o<u;o++){if(p=
s.charCodeAt(o),a&&p===37&&o+2<u&&/^[0-9a-f]{2}$/i.test(s.slice(o+1,o+3))){x+=s.slice(o,o+3),o+=2;continue}if(p<128){x+=k[p];continue}if(p>=55296&&p<=57343){if(p>=55296&&p<=56319&&o+1<u&&(y=s.charCodeAt(o+1),y>=56320&&y<=57343)){x+=encodeURIComponent(s[o]+s[o+1]),o++;continue}x+="%EF%BF%BD";continue}x+=encodeURIComponent(s[o])}return x}r.defaultChars=";/?:@&=+$,-_.!~*'()#",r.componentChars="-_.!~*\
'()",e.exports=r}),et=F((t,e)=>{var n={amp:"&",lt:"<",gt:">",quot:'"',apos:"'",nbsp:"\xA0",copy:"\xA9",reg:"\xAE",trade:"\u2122",hellip:"\u2026",mdash:"\u2014",ndash:"\u2013",lsquo:"\u2018",rsquo:"\u2019",ldquo:"\u201C",rdquo:"\u201D",bull:"\u2022",dagger:"\u2020",deg:"\xB0",plusmn:"\xB1",times:"\xD7",divide:"\xF7",frac12:"\xBD",laquo:"\xAB",raquo:"\xBB",sect:"\xA7",para:"\xB6",middot:"\xB7",eacute:"\
\xE9",egrave:"\xE8",agrave:"\xE0",ccedil:"\xE7",uuml:"\xFC",ouml:"\xF6",auml:"\xE4",szlig:"\xDF",ntilde:"\xF1",aacute:"\xE1",iacute:"\xED",oacute:"\xF3",uacute:"\xFA",euro:"\u20AC",pound:"\xA3",yen:"\xA5",cent:"\xA2",alpha:"\u03B1",beta:"\u03B2",gamma:"\u03B3",delta:"\u03B4",pi:"\u03C0",lambda:"\u03BB",mu:"\u03BC",infin:"\u221E",ne:"\u2260",le:"\u2264",ge:"\u2265",larr:"\u2190",rarr:"\u2192",harr:"\
\u2194"};function i(r){return r.replace(/&(?:#[xX]([0-9a-fA-F]+)|#(\d+)|([a-zA-Z][a-zA-Z0-9]*));/g,(s,l,a,o)=>l?String.fromCodePoint(parseInt(l,16)||65533):a?String.fromCodePoint(parseInt(a,10)||65533):n[o]!==void 0?n[o]:s)}e.exports={decodeHTML:i,decodeHTMLStrict:i,encodeHTML:r=>r,escape:r=>r.replace(/[&<>"]/g,s=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[s])}}),U,nt,it,d,h,g,j,H,A,P,yt,Lt,
rt,ut,Nt,O,c,pt,ft,dt,_t,T,st,$,G,C,N,X,wt=z(()=>{"use strict";U=L(tt(),1),nt=L(et(),1),it=92,d="&(?:#x[a-f0-9]{1,6}|#[0-9]{1,7}|[a-z][a-z0-9]{1,31});",h="[A-Za-z][A-Za-z0-9-]*",g="[a-zA-Z_:][a-zA-Z0-9:._-]*",j="[^\"'=<>`\\x00-\\x20]+",H="'[^']*'",A='"[^"]*"',P="(?:"+j+"|"+H+"|"+A+")",yt="(?:\\s*=\\s*"+P+")",Lt="(?:\\s+"+g+yt+"?)",rt="<"+h+Lt+"*\\s*/?>",ut="</"+h+"\\s*[>]",Nt="<!-->|<!--->|<!--[\\s\
\\S]*?-->",O="[<][?][\\s\\S]*?[?][>]",c="<![A-Za-z]+[^>]*>",pt="<!\\[CDATA\\[[\\s\\S]*?\\]\\]>",ft="(?:"+rt+"|"+ut+"|"+Nt+"|"+O+"|"+c+"|"+pt+")",dt=new RegExp("^"+ft),_t=/[\\&]/,T="[!\"#$%&'()*+,./:;<=>?@[\\\\\\]^_`{|}~-]",st=new RegExp("\\\\"+T+"|"+d,"gi"),$='[&<>"]',G=new RegExp($,"g"),C=function(t){return t.charCodeAt(0)===it?t.charAt(1):(0,nt.decodeHTMLStrict)(t)},N=function(t){return _t.test(
t)?t.replace(st,C):t},X=function(t){try{return(0,U.default)(t)}catch{return t}}});function M(t){return at(t)}var at,gt,mt,Bn=z(()=>{"use strict";String.fromCodePoint?at=function(t){try{return String.fromCodePoint(t)}catch(e){if(e instanceof RangeError)return"\uFFFD";throw e}}:(gt=String.fromCharCode,mt=Math.floor,at=function(){var t=16384,e=[],n,i,r=-1,s=arguments.length;if(!s)return"";for(var l="";++r<
s;){var a=Number(arguments[r]);if(!isFinite(a)||a<0||a>1114111||mt(a)!==a)return"\uFFFD";a<=65535?e.push(a):(a-=65536,n=(a>>10)+55296,i=a%1024+56320,e.push(n,i)),(r+1===s||e.length>t)&&(l+=gt.apply(null,e),e.length=0)}return l})});function Dn(t){return{subject:"",delimiters:null,brackets:null,pos:0,refmap:{},match:xe,peek:Ce,spnl:ye,parseBackticks:Le,parseBackslash:Ne,parseAutolink:we,parseHtmlTag:Oe,
scanDelims:Be,handleDelim:De,parseLinkTitle:je,parseLinkDestination:Pe,parseLinkLabel:ze,parseOpenBracket:Se,parseBang:Te,parseCloseBracket:$e,addBracket:Fe,removeBracket:Re,parseEntity:Ue,parseString:Me,parseNewline:Ze,parseReference:Ie,parseInline:qe,processEmphasis:Ee,removeDelimiter:Ae,options:t||{},parse:He}}var Vt,vt,Ot,jt,Bt,kt,te,Pt,ee,zt,ne,St,ie,Tt,Dt,re,Z,I,At,$t,Et,se,ae,Ft,le,oe,Rt,ce,
he,ue,pe,fe,de,_e,ge,Ut,Mt,me,ve,Zt,ke,be,w,It,xe,Ce,ye,Le,Ne,we,Oe,Be,De,Ae,qt,Ee,je,Pe,ze,Se,Te,$e,Fe,Re,Ue,Me,Ze,Ie,qe,He,Ge,An=z(()=>{"use strict";V(),wt(),Bn(),Vt=L(et(),1),vt=X,Ot=N,jt=10,Bt=42,kt=95,te=96,Pt=91,ee=93,zt=60,ne=33,St=92,ie=38,Tt=40,Dt=41,re=58,Z=39,I=34,At=126,$t=T,Et="\\\\"+$t,se=d,ae=dt,Ft=new RegExp(/^[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~\p{P}\p{S}]/u),le=new RegExp('^(?:"\
('+Et+`|\\\\[^\\\\]|[^\\\\"\\x00])*"|'(`+Et+"|\\\\[^\\\\]|[^\\\\'\\x00])*'|\\(("+Et+"|\\\\[^\\\\]|[^\\\\()\\x00])*\\))"),oe=/^(?:<(?:[^<>\n\\\x00]|\\.)*>)/,Rt=new RegExp("^"+$t),ce=new RegExp("^"+se,"i"),he=/`+/,ue=/^`+/,pe=/\.\.\./g,fe=/--+/g,de=/^<([a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*)>/,_e=/^<[A-Za-z][A-Za-z0-9.+-]{1,31}:[^<>\x00-\x20]*>/i,
ge=/^ *(?:\n *)?/,Ut=/^[ \t\n\x0b\x0c\x0d]/,Mt=/^\s/,me=/ *$/,ve=/^ */,Zt=/^ *(?:\n|$)/,ke=/^\[(?:[^\\\[\]]|\\.){0,1000}\]/s,be=/^[^\n`\[\]\\!<&*_'"~]+/m,w=function(t){var e=new _("text");return e._literal=t,e},It=function(t){return t.slice(1,t.length-1).trim().replace(/[ \t\r\n]+/g," ").toLowerCase().toUpperCase()},xe=function(t){var e=t.exec(this.subject.slice(this.pos));return e===null?null:(this.
pos+=e.index+e[0].length,e[0])},Ce=function(){return this.pos<this.subject.length?this.subject.charCodeAt(this.pos):-1},ye=function(){return this.match(ge),!0},Le=function(t){var e=this.match(ue);if(e===null)return!1;for(var n=this.pos,i,r,s;(i=this.match(he))!==null;)if(i===e)return r=new _("code"),s=this.subject.slice(n,this.pos-e.length).replace(/\n/gm," "),s.length>0&&s.match(/[^ ]/)!==null&&s[0]==
" "&&s[s.length-1]==" "?r._literal=s.slice(1,s.length-1):r._literal=s,t.appendChild(r),!0;return this.pos=n,t.appendChild(w(e)),!0},Ne=function(t){var e=this.subject,n;return this.pos+=1,this.peek()===jt?(this.pos+=1,n=new _("linebreak"),t.appendChild(n)):Rt.test(e.charAt(this.pos))?(t.appendChild(w(e.charAt(this.pos))),this.pos+=1):t.appendChild(w("\\")),!0},we=function(t){var e,n,i;return(e=this.
match(de))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=vt("mailto:"+n),i._title="",i.appendChild(w(n)),t.appendChild(i),!0):(e=this.match(_e))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=vt(n),i._title="",i.appendChild(w(n)),t.appendChild(i),!0):!1},Oe=function(t){var e=this.match(ae);if(e===null)return!1;var n=new _("html_inline");return n._literal=e,t.appendChild(n),!0},Be=
function(t){var e=0,n,i,r,s=this.pos,l,a,o,u,p,y,k,x;if(t===Z||t===I)e++,this.pos++;else for(;this.peek()===t;)e++,this.pos++;return e===0?null:(n=s===0?`
`:this.subject.charAt(s-1),r=this.peek(),r===-1?i=`
`:i=M(r),p=Mt.test(i),y=Ft.test(i),k=Mt.test(n),x=Ft.test(n),l=!p&&(!y||k||x),a=!k&&(!x||p||y),t===kt?(o=l&&(!a||x),u=a&&(!l||y)):t===Z||t===I?(o=l&&!a,u=a):(o=l,u=a),this.pos=s,{numdelims:e,can_open:o,can_close:u})},De=function(t,e){var n=this.scanDelims(t);if(!n)return!1;var i=n.numdelims,r=this.pos,s;this.pos+=i,t===Z?s="\u2019":t===I?s="\u201C":s=this.subject.slice(r,this.pos);var l=w(s);return e.
appendChild(l),(n.can_open||n.can_close)&&(this.options.smart||t!==Z&&t!==I)&&(this.delimiters={cc:t,numdelims:i,origdelims:i,node:l,previous:this.delimiters,next:null,can_open:n.can_open,can_close:n.can_close},this.delimiters.previous!==null&&(this.delimiters.previous.next=this.delimiters)),!0},Ae=function(t){t.previous!==null&&(t.previous.next=t.next),t.next===null?this.delimiters=t.previous:t.next.
previous=t.previous},qt=function(t,e){t.next!==e&&(t.next=e,e.previous=t)},Ee=function(t){for(var e,n,i,r,s,l,a,o,u,p,y=[],k,x=!1,ot=0;ot<14;ot++)y[ot]=t;for(n=this.delimiters;n!==null&&n.previous!==t;)n=n.previous;for(;n!==null;){var ct=n.cc;if(!n.can_close)n=n.next;else{switch(e=n.previous,p=!1,ct){case Z:k=0;break;case I:k=1;break;case kt:k=2+(n.can_open?3:0)+n.origdelims%3;break;case Bt:k=8+(n.
can_open?3:0)+n.origdelims%3;break;case At:k=14;break}for(;e!==null&&e!==t&&e!==y[k];){if(x=(n.can_open||e.can_close)&&n.origdelims%3!==0&&(e.origdelims+n.origdelims)%3===0,e.cc===n.cc&&e.can_open&&!x){p=!0;break}e=e.previous}if(i=n,ct===At)if(!p||n.numdelims<2||e.numdelims<2)n=n.next;else{r=e.node,s=n.node,e.numdelims-=2,n.numdelims-=2,r._literal=r._literal.slice(0,r._literal.length-2),s._literal=
s._literal.slice(0,s._literal.length-2);for(var wn=new _("strikethrough"),Ct=r._next;Ct&&Ct!==s;){var zn=Ct._next;wn.appendChild(Ct),Ct=zn}r.insertAfter(wn),qt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else if(ct===Bt||ct===kt)if(!p)n=n.next;else{a=n.numdelims>=2&&e.numdelims>=2?2:1,r=e.node,s=n.node,e.numdelims-=a,
n.numdelims-=a,r._literal=r._literal.slice(0,r._literal.length-a),s._literal=s._literal.slice(0,s._literal.length-a);var On=new _(a===1?"emph":"strong");for(o=r._next;o&&o!==s;)u=o._next,o.unlink(),On.appendChild(o),o=u;r.insertAfter(On),qt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else ct===Z?(n.node._literal="\u2019",
p&&(e.node._literal="\u2018"),n=n.next):ct===I&&(n.node._literal="\u201D",p&&(e.node.literal="\u201C"),n=n.next);p||(y[k]=i.previous,i.can_open||this.removeDelimiter(i))}}for(;this.delimiters!==null&&this.delimiters!==t;)this.removeDelimiter(this.delimiters)},je=function(){var t=this.match(le);return t===null?null:Ot(t.slice(1,-1))},Pe=function(){var t=this.match(oe);if(t===null){if(this.peek()===
zt)return null;for(var e=this.pos,n=0,i;(i=this.peek())!==-1;)if(i===St&&Rt.test(this.subject.charAt(this.pos+1)))this.pos+=1,this.peek()!==-1&&(this.pos+=1);else if(i===Tt)this.pos+=1,n+=1;else if(i===Dt){if(n<1)break;this.pos+=1,n-=1}else{if(Ut.exec(M(i))!==null)break;this.pos+=1}return this.pos===e&&i!==Dt||n!==0?null:(t=this.subject.slice(e,this.pos),vt(Ot(t)))}else return vt(Ot(t.slice(1,-1)))},
ze=function(){var t=this.match(ke);return t===null||t.length>1001?0:t.length},Se=function(t){var e=this.pos,n=this.match(/^\[\^[^\]]+\]/);if(n){var i=new _("footnote_reference");return i._label=n.slice(2,-1),t.appendChild(i),!0}this.pos+=1;var r=w("[");return t.appendChild(r),this.addBracket(r,e,!1),!0},Te=function(t){var e=this.pos;if(this.pos+=1,this.peek()===Pt){this.pos+=1;var n=w("![");t.appendChild(
n),this.addBracket(n,e+1,!0)}else t.appendChild(w("!"));return!0},$e=function(t){var e,n,i,r,s=!1,l,a;if(this.pos+=1,e=this.pos,a=this.brackets,a===null)return t.appendChild(w("]")),!0;if(!a.active)return t.appendChild(w("]")),this.removeBracket(),!0;n=a.image;var o=this.pos;if(this.peek()===Tt&&(this.pos++,this.spnl()&&(i=this.parseLinkDestination())!==null&&this.spnl()&&(Ut.test(this.subject.charAt(
this.pos-1))&&(r=this.parseLinkTitle())||!0)&&this.spnl()&&this.peek()===Dt?(this.pos+=1,s=!0):this.pos=o),!s){var u=this.pos,p=this.parseLinkLabel();if(p>2?l=this.subject.slice(u,u+p):a.bracketAfter||(l=this.subject.slice(a.index,e)),p===0&&(this.pos=o),l){var y=this.refmap[It(l)];y&&(i=y.destination,r=y.title,s=!0)}}if(s){var k=new _(n?"image":"link");k._destination=i,k._title=r||"";var x,ot;for(x=
a.node._next;x;)ot=x._next,x.unlink(),k.appendChild(x),x=ot;if(t.appendChild(k),this.processEmphasis(a.previousDelimiter),this.removeBracket(),a.node.unlink(),!n)for(a=this.brackets;a!==null;)a.image||(a.active=!1),a=a.previous;return!0}else return this.removeBracket(),this.pos=e,t.appendChild(w("]")),!0},Fe=function(t,e,n){this.brackets!==null&&(this.brackets.bracketAfter=!0),this.brackets={node:t,
previous:this.brackets,previousDelimiter:this.delimiters,index:e,image:n,active:!0}},Re=function(){this.brackets=this.brackets.previous},Ue=function(t){var e;return(e=this.match(ce))?(t.appendChild(w((0,Vt.decodeHTMLStrict)(e))),!0):!1},Me=function(t){var e;return(e=this.match(be))?(this.options.smart?t.appendChild(w(e.replace(pe,"\u2026").replace(fe,function(n){var i=0,r=0;return n.length%3===0?r=
n.length/3:n.length%2===0?i=n.length/2:n.length%3===2?(i=1,r=(n.length-2)/3):(i=2,r=(n.length-4)/3),"\u2014".repeat(r)+"\u2013".repeat(i)}))):t.appendChild(w(e)),!0):!1},Ze=function(t){this.pos+=1;var e=t._lastChild;if(e&&e.type==="text"&&e._literal[e._literal.length-1]===" "){var n=e._literal[e._literal.length-2]===" ";e._literal=e._literal.replace(me,""),t.appendChild(new _(n?"linebreak":"softbr\
eak"))}else t.appendChild(new _("softbreak"));return this.match(ve),!0},Ie=function(t,e){this.subject=t,this.pos=0;var n,i,r,s,l=this.pos;if(s=this.parseLinkLabel(),s===0)return 0;if(n=this.subject.slice(0,s),this.peek()===re)this.pos++;else return this.pos=l,0;if(this.spnl(),i=this.parseLinkDestination(),i===null)return this.pos=l,0;var a=this.pos;this.spnl(),this.pos!==a&&(r=this.parseLinkTitle()),
r===null&&(this.pos=a);var o=!0;if(this.match(Zt)===null&&(r===null?o=!1:(r=null,this.pos=a,o=this.match(Zt)!==null)),!o)return this.pos=l,0;var u=It(n);return u===""?(this.pos=l,0):(e[u]||(e[u]={destination:i,title:r===null?"":r}),this.pos-l)},qe=function(t){var e=!1,n=this.peek();if(n===-1)return!1;switch(n){case jt:e=this.parseNewline(t);break;case St:e=this.parseBackslash(t);break;case te:e=this.
parseBackticks(t);break;case Bt:case kt:case At:e=this.handleDelim(n,t);break;case Z:case I:e=this.options.smart&&this.handleDelim(n,t);break;case Pt:e=this.parseOpenBracket(t);break;case ne:e=this.parseBang(t);break;case ee:e=this.parseCloseBracket(t);break;case zt:e=this.parseAutolink(t)||this.parseHtmlTag(t);break;case ie:e=this.parseEntity(t);break;default:e=this.parseString(t);break}return e||
(this.pos+=1,t.appendChild(w(M(n)))),!0},He=function(t){for(this.subject=t._string_content.trim(),this.pos=0,this.delimiters=null,this.brackets=null;this.parseInline(t););t._string_content=null,this.processEmphasis(null)},Ge=Dn}),Xe={};ht(Xe,{default:()=>Nn});function En(t){return{doc:new Yt,blocks:Qt,blockStarts:mn,tip:this.doc,oldtip:this.doc,currentLine:"",lineNumber:0,offset:0,column:0,nextNonspace:0,
nextNonspaceColumn:0,indent:0,indented:!1,blank:!1,partiallyConsumedTab:!1,allClosed:!0,lastMatchedContainer:this.doc,refmap:{},lastLineLength:0,inlineParser:new Ge(t),findNextNonspace:bn,advanceOffset:vn,advanceNextNonspace:kn,addLine:un,addChild:pn,incorporateLine:xn,finalize:Cn,processInlines:yn,closeUnmatchedBlocks:_n,parse:Ln,options:t||{}}}var bt,Ht,Ke,Gt,We,Xt,Kt,Je,Qe,Ye,Ve,tn,xt,en,Wt,nn,
rn,sn,an,ln,on,cn,hn,lt,E,Jt,un,pn,fn,dn,_n,gn,Qt,mn,vn,kn,bn,xn,Cn,yn,Yt,Ln,Nn,jn=z(()=>{"use strict";V(),wt(),An(),bt=4,Ht=9,Ke=10,Gt=62,We=60,Xt=32,Kt=91,Je=[/./,/^<(?:script|pre|textarea|style)(?:\s|>|$)/i,/^<!--/,/^<[?]/,/^<![A-Za-z]/,/^<!\[CDATA\[/,/^<[/]?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[123456]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|nav|noframes|ol|optgroup|option|p|param|section|search|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?:\s|[/]?[>]|$)/i,
new RegExp("^(?:"+rt+"|"+ut+")\\s*$","i")],Qe=[/./,/<\/(?:script|pre|textarea|style)>/i,/-->/,/\?>/,/>/,/\]\]>/],Ye=/^(?:\*[ \t]*){3,}$|^(?:_[ \t]*){3,}$|^(?:-[ \t]*){3,}$/,Ve=/^\[\^([^\]]+)\]:[ \t]*/,tn=/^\|?[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)*\|?[ \t]*$/,xt=function(t){var e=[],n="",i,r;for(t=t.trim().replace(/^\|/,"").replace(/\|[ \t]*$/,""),i=0;i<t.length;i++)r=t.charAt(i),r==="\\"&&t.charAt(
i+1)==="|"?(n+="|",i++):r==="|"?(e.push(n.trim()),n=""):n+=r;return e.push(n.trim()),e},en=/^[#`~*+_=<>0-9|:[-]/,Wt=/[^ \t\f\v\r\n]/,nn=/^[*+-]/,rn=/^(\d{1,9})([.)])/,sn=/^#{1,6}(?:[ \t]+|$)/,an=/^`{3,}(?!.*`)|^~{3,}/,ln=/^(?:`{3,}|~{3,})(?=[ \t]*$)/,on=/^(?:=+|-+)[ \t]*$/,cn=/\r\n|\n|\r/,hn=function(t){return!Wt.test(t)},lt=function(t){return t===Xt||t===Ht},E=function(t,e){return e<t.length?t.charCodeAt(
e):-1},Jt=function(t){return t.next&&t.sourcepos[1][0]!==t.next.sourcepos[0][0]-1},un=function(){if(this.partiallyConsumedTab){this.offset+=1;var t=4-this.column%4;this.tip._string_content+=" ".repeat(t)}this.tip._string_content+=this.currentLine.slice(this.offset)+`
`},pn=function(t,e){for(;!this.blocks[this.tip.type].canContain(t);)this.finalize(this.tip,this.lineNumber-1);var n=e+1,i=new _(t,[[this.lineNumber,n],[0,0]]);return i._string_content="",this.tip.appendChild(i),this.tip=i,i},fn=function(t,e){var n=t.currentLine.slice(t.nextNonspace),i,r,s,l,a={type:null,tight:!0,bulletChar:null,start:null,delimiter:null,padding:null,markerOffset:t.indent};if(t.indent>=
4)return null;if(i=n.match(nn))a.type="bullet",a.bulletChar=i[0][0];else if((i=n.match(rn))&&(e.type!=="paragraph"||i[1]==1))a.type="ordered",a.start=parseInt(i[1]),a.delimiter=i[2];else return null;if(r=E(t.currentLine,t.nextNonspace+i[0].length),!(r===-1||r===Ht||r===Xt)||e.type==="paragraph"&&!t.currentLine.slice(t.nextNonspace+i[0].length).match(Wt))return null;t.advanceNextNonspace(),t.advanceOffset(
i[0].length,!0),s=t.column,l=t.offset;do t.advanceOffset(1,!0),r=E(t.currentLine,t.offset);while(t.column-s<5&&lt(r));var o=E(t.currentLine,t.offset)===-1,u=t.column-s;return u>=5||u<1||o?(a.padding=i[0].length+1,t.column=s,t.offset=l,lt(E(t.currentLine,t.offset))&&t.advanceOffset(1,!0)):a.padding=i[0].length+u,a},dn=function(t,e){return t.type===e.type&&t.delimiter===e.delimiter&&t.bulletChar===e.
bulletChar},_n=function(){if(!this.allClosed){for(;this.oldtip!==this.lastMatchedContainer;){var t=this.oldtip._parent;this.finalize(this.oldtip,this.lineNumber-1),this.oldtip=t}this.allClosed=!0}},gn=function(t,e){for(var n,i,r=e.walker(),s=[];n=r.next();)if(i=n.node,n.entering&&i.type==="paragraph"){for(var l,a=!1;E(i._string_content,0)===Kt&&(l=t.inlineParser.parseReference(i._string_content,t.
refmap));){let o=i._string_content.slice(0,l);i._string_content=i._string_content.slice(l),a=!0;let u=o.split(`
`);i.sourcepos[0][0]+=u.length-1}a&&hn(i._string_content)&&s.push(i)}for(i of s)i.unlink()},Qt={document:{continue:function(){return 0},finalize:function(t,e){gn(t,e)},canContain:function(t){return t!=="item"},acceptsLines:!1},list:{continue:function(){return 0},finalize:function(t,e){for(var n=e._firstChild;n;){if(n._next&&Jt(n)){e._listData.tight=!1;break}for(var i=n._firstChild;i;){if(i._next&&
Jt(i)){e._listData.tight=!1;break}i=i._next}n=n._next}e.sourcepos[1]=e._lastChild.sourcepos[1]},canContain:function(t){return t==="item"},acceptsLines:!1},block_quote:{continue:function(t){var e=t.currentLine;if(!t.indented&&E(e,t.nextNonspace)===Gt)t.advanceNextNonspace(),t.advanceOffset(1,!1),lt(E(e,t.offset))&&t.advanceOffset(1,!0);else return 1;return 0},finalize:function(){},canContain:function(t){
return t!=="item"},acceptsLines:!1},item:{continue:function(t,e){if(t.blank){if(e._firstChild==null)return 1;t.advanceNextNonspace()}else if(t.indent>=e._listData.markerOffset+e._listData.padding)t.advanceOffset(e._listData.markerOffset+e._listData.padding,!0);else return 1;return 0},finalize:function(t,e){e._lastChild?e.sourcepos[1]=e._lastChild.sourcepos[1]:(e.sourcepos[1][0]=e.sourcepos[0][0],e.
sourcepos[1][1]=e._listData.markerOffset+e._listData.padding)},canContain:function(t){return t!=="item"},acceptsLines:!1},heading:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},thematic_break:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},code_block:{continue:function(t,e){var n=t.currentLine,
i=t.indent;if(e._isFenced){var r=i<=3&&n.charAt(t.nextNonspace)===e._fenceChar&&n.slice(t.nextNonspace).match(ln);if(r&&r[0].length>=e._fenceLength)return t.lastLineLength=t.offset+i+r[0].length,t.finalize(e,t.lineNumber),2;for(var s=e._fenceOffset;s>0&&lt(E(n,t.offset));)t.advanceOffset(1,!0),s--}else if(i>=bt)t.advanceOffset(bt,!0);else if(t.blank)t.advanceNextNonspace();else return 1;return 0},
finalize:function(t,e){if(e._isFenced){var n=e._string_content,i=n.indexOf(`
`),r=n.slice(0,i),s=n.slice(i+1);e.info=N(r.trim()),e._literal=s}else{for(var l=e._string_content.split(`
`);/^[ \t]*$/.test(l[l.length-1]);)l.pop();e._literal=l.join(`
`)+`
`,e.sourcepos[1][0]=e.sourcepos[0][0]+l.length-1,e.sourcepos[1][1]=e.sourcepos[0][1]+l[l.length-1].length-1}e._string_content=null},canContain:function(){return!1},acceptsLines:!0},html_block:{continue:function(t,e){return t.blank&&(e._htmlBlockType===6||e._htmlBlockType===7)?1:0},finalize:function(t,e){e._literal=e._string_content.replace(/\n$/,""),e._string_content=null},canContain:function(){return!1},
acceptsLines:!0},footnote_definition:{continue:function(t){return t.blank?0:t.indent>=4?(t.advanceOffset(4,!0),0):t.tip.type==="paragraph"?0:1},finalize:function(){},canContain:function(t){return t!=="item"&&t!=="footnote_definition"},acceptsLines:!1},table:{continue:function(t){return t.blank?1:0},finalize:function(t,e){var n=e._string_content.replace(/\n$/,"").split(`
`),i=xt(n[1]),r=i.map(function(p){var y=p.charAt(0)===":",k=p.charAt(p.length-1)===":";return y&&k?"center":k?"right":y?"left":null}),s,l,a,o,u;for(s=0;s<n.length;s++)if(s!==1){for(a=xt(n[s]),o=new _("table_row"),o._isHeading=s===0,l=0;l<i.length;l++)u=new _("table_cell"),u._align=r[l],u._string_content=a[l]===void 0?"":a[l],o.appendChild(u);e.appendChild(o)}e._string_content=null},canContain:function(t){
return t==="table_row"},acceptsLines:!0},paragraph:{continue:function(t){return t.blank?1:0},finalize:function(){},canContain:function(){return!1},acceptsLines:!0}},mn=[function(t){if(t.indented)return 0;var e=t.currentLine.slice(t.nextNonspace).match(Ve);if(!e)return 0;t.closeUnmatchedBlocks(),t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1);var n=t.addChild("footnote_definition",t.nextNonspace);
return n._label=e[1],1},function(t,e){if(t.indented||e.type!=="paragraph")return 0;var n=t.currentLine.slice(t.nextNonspace);if(n.indexOf("|")===-1||!tn.test(n))return 0;var i=e._string_content.replace(/\n$/,"").split(`
`),r=i[i.length-1];if(!r||r.indexOf("|")===-1||xt(r).length!==xt(n).length)return 0;var s=i.slice(0,i.length-1).join(`
`);e._string_content=s===""?"":s+`
`,t.closeUnmatchedBlocks();var l=s==="",a=t.addChild("table",t.nextNonspace);return l&&e.unlink(),a._string_content=r+`
`,2},function(t){return!t.indented&&E(t.currentLine,t.nextNonspace)===Gt?(t.advanceNextNonspace(),t.advanceOffset(1,!1),lt(E(t.currentLine,t.offset))&&t.advanceOffset(1,!0),t.closeUnmatchedBlocks(),t.addChild("block_quote",t.nextNonspace),1):0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(sn))){t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1),t.closeUnmatchedBlocks();
var n=t.addChild("heading",t.nextNonspace);return n.level=e[0].trim().length,n._string_content=t.currentLine.slice(t.offset).replace(/^[ \t]*#+[ \t]*$/,"").replace(/[ \t]+#+[ \t]*$/,""),t.advanceOffset(t.currentLine.length-t.offset),2}else return 0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(an))){var n=e[0].length;t.closeUnmatchedBlocks();var i=t.addChild("code\
_block",t.nextNonspace);return i._isFenced=!0,i._fenceLength=n,i._fenceChar=e[0][0],i._fenceOffset=t.indent,t.advanceNextNonspace(),t.advanceOffset(n,!1),2}else return 0},function(t,e){if(!t.indented&&E(t.currentLine,t.nextNonspace)===We){var n=t.currentLine.slice(t.nextNonspace),i;for(i=1;i<=7;i++)if(Je[i].test(n)&&(i<7||e.type!=="paragraph"&&!(!t.allClosed&&!t.blank&&t.tip.type==="paragraph"))){
t.closeUnmatchedBlocks();var r=t.addChild("html_block",t.offset);return r._htmlBlockType=i,2}}return 0},function(t,e){var n;if(!t.indented&&e.type==="paragraph"&&(n=t.currentLine.slice(t.nextNonspace).match(on))){t.closeUnmatchedBlocks();for(var i;E(e._string_content,0)===Kt&&(i=t.inlineParser.parseReference(e._string_content,t.refmap));)e._string_content=e._string_content.slice(i);if(e._string_content.
length>0){var r=new _("heading",e.sourcepos);return r.level=n[0][0]==="="?1:2,r._string_content=e._string_content,e.insertAfter(r),e.unlink(),t.tip=r,t.advanceOffset(t.currentLine.length-t.offset,!1),2}else return 0}else return 0},function(t){return!t.indented&&Ye.test(t.currentLine.slice(t.nextNonspace))?(t.closeUnmatchedBlocks(),t.addChild("thematic_break",t.nextNonspace),t.advanceOffset(t.currentLine.
length-t.offset,!1),2):0},function(t,e){var n;return(!t.indented||e.type==="list")&&(n=fn(t,e))?(t.closeUnmatchedBlocks(),(t.tip.type!=="list"||!dn(e._listData,n))&&(e=t.addChild("list",t.nextNonspace),e._listData=n),e=t.addChild("item",t.nextNonspace),e._listData=n,1):0},function(t){return t.indented&&t.tip.type!=="paragraph"&&!t.blank?(t.advanceOffset(bt,!0),t.closeUnmatchedBlocks(),t.addChild("\
code_block",t.offset),2):0}],vn=function(t,e){for(var n=this.currentLine,i,r,s;t>0&&(s=n[this.offset]);)s==="	"?(i=4-this.column%4,e?(this.partiallyConsumedTab=i>t,r=i>t?t:i,this.column+=r,this.offset+=this.partiallyConsumedTab?0:1,t-=r):(this.partiallyConsumedTab=!1,this.column+=i,this.offset+=1,t-=1)):(this.partiallyConsumedTab=!1,this.offset+=1,this.column+=1,t-=1)},kn=function(){this.offset=this.
nextNonspace,this.column=this.nextNonspaceColumn,this.partiallyConsumedTab=!1},bn=function(){for(var t=this.currentLine,e=this.offset,n=this.column,i;(i=t.charAt(e))!=="";)if(i===" ")e++,n++;else if(i==="	")e++,n+=4-n%4;else break;this.blank=i===`
`||i==="\r"||i==="",this.nextNonspace=e,this.nextNonspaceColumn=n,this.indent=this.nextNonspaceColumn-this.column,this.indented=this.indent>=bt},xn=function(t){var e=!0,n,i=this.doc;this.oldtip=this.tip,this.offset=0,this.column=0,this.blank=!1,this.partiallyConsumedTab=!1,this.lineNumber+=1,t.indexOf("\0")!==-1&&(t=t.replace(/\0/g,"\uFFFD")),this.currentLine=t;for(var r;(r=i._lastChild)&&r._open;){
switch(i=r,this.findNextNonspace(),this.blocks[i.type].continue(this,i)){case 0:break;case 1:e=!1;break;case 2:return;default:throw"continue returned illegal value, must be 0, 1, or 2"}if(!e){i=i._parent;break}}this.allClosed=i===this.oldtip,this.lastMatchedContainer=i;for(var s=i.type!=="paragraph"&&i.type!=="table"&&Qt[i.type].acceptsLines,l=this.blockStarts,a=l.length;!s;){if(this.findNextNonspace(),
!this.indented&&!en.test(t.slice(this.nextNonspace))){this.advanceNextNonspace();break}for(var o=0;o<a;){var u=l[o](this,i);if(u===1){i=this.tip;break}else if(u===2){i=this.tip,s=!0;break}else o++}if(o===a){this.advanceNextNonspace();break}}!this.allClosed&&!this.blank&&this.tip.type==="paragraph"?this.addLine():(this.closeUnmatchedBlocks(),n=i.type,this.blocks[n].acceptsLines?(this.addLine(),n===
"html_block"&&i._htmlBlockType>=1&&i._htmlBlockType<=5&&Qe[i._htmlBlockType].test(this.currentLine.slice(this.offset))&&(this.lastLineLength=t.length,this.finalize(i,this.lineNumber))):this.offset<t.length&&!this.blank&&(i=this.addChild("paragraph",this.offset),this.advanceNextNonspace(),this.addLine())),this.lastLineLength=t.length},Cn=function(t,e){var n=t._parent;t._open=!1,t.sourcepos[1]=[e,this.
lastLineLength],this.blocks[t.type].finalize(this,t),this.tip=n},yn=function(t){var e,n,i,r=t.walker();for(this.inlineParser.refmap=this.refmap,this.inlineParser.options=this.options;n=r.next();)e=n.node,i=e.type,!n.entering&&(i==="paragraph"||i==="heading"||i==="table_cell")&&this.inlineParser.parse(e)},Yt=function(){var t=new _("document",[[1,1],[0,0]]);return t},Ln=function(t){this.doc=new Yt,this.
tip=this.doc,this.refmap={},this.lineNumber=0,this.lastLineLength=0,this.offset=0,this.column=0,this.lastMatchedContainer=this.doc,this.currentLine="",this.options.time&&console.time("preparing input");var e=t.split(cn),n=e.length;t.charCodeAt(t.length-1)===Ke&&(n-=1),this.options.time&&console.timeEnd("preparing input"),this.options.time&&console.time("block parsing");for(var i=0;i<n;i++)this.incorporateLine(
e[i]);for(;this.tip;)this.finalize(this.tip,n);return this.options.time&&console.timeEnd("block parsing"),this.options.time&&console.time("inline parsing"),this.processInlines(this.doc),this.options.time&&console.timeEnd("inline parsing"),this.doc},Nn=En}),Pn=F((t,e)=>{var n=(jn(),v(Xe));e.exports={Parser:n.Parser||n.default||n}});return Pn()})();function protectBlockBody(f){return f.split(`
`).map(function(b){return b.replace(/^([ \t]*)(,*)(\*|#\+)/,"$1$2,$3")}).join(`
`)}function codeSpan(f){return f.indexOf("=")===-1?"="+f+"=":f.indexOf("~")===-1?"~"+f+"~":f}function escapeLinkDesc(f,b){var B=String(f).replace(/\]\]/g,"]\\zwnj{}]");return B[0]==="]"&&b==="]"&&(B="\\zwnj{}"+B),B}function escapeCell(f){return String(f).replace(/\|/g,"\\vert{}")}function escapeLinkPath(f){return String(f).replace(/([\[\]\\])/g,"\\$1")}function fnLabel(f){return String(f).trim().toLowerCase().
replace(/[^a-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"")||"fn"}function renderOrg(f,b){for(var B={},q={},K=f.walker(),W,z,F,ht;W=K.next();)if(!(!W.entering||W.node.type!=="footnote_definition")&&(z=W.node._label,B[z]===void 0)){for(F=fnLabel(z),ht=1;q[F];)ht++,F=fnLabel(z)+"-"+ht;q[F]=1,B[z]=F}function J(C){return B[C]!==void 0?B[C]:null}renderOrg.warn||(renderOrg.warn=[]);var L=[],v="",Q=[],S=[],R=0,Y=0,
D=0,m=0,_=!0,V=!1,tt=0,et=!1,U=!1,nt=0,it=0;function d(){return Q.join("")}function h(C){C&&(v+=C,_=!1)}function g(){S.length&&(v=v.replace(/^(\s*(?:-|\d+\.) )\[x\] /,"$1[X] ")),V&&!d()&&/^\*+\s/.test(v)&&renderOrg.warn.push({n:L.length+1,t:v}),L.push(v),v="",_=!0}function j(){v!==""&&g()}function H(){L.length&&L[L.length-1]!==""&&L.push("")}function A(C){var N=C.sourcepos;if(!N){H();return}tt&&N[0][0]>
tt+1&&H()}function P(C){C.sourcepos&&(tt=C.sourcepos[1][0])}function yt(C){var N=et?b.escapeCell(C):C;R>0&&(N=b.escapeLinkDesc(N,v.slice(-1))),h(N)}function Lt(){v.slice(-1)==="]"&&h("\\zwnj{}"),h("]]")}function rt(C){C.replace(/\n$/,"").split(`
`).forEach(function(N){h(d()+N),g()})}function ut(C){var N=C.replace(/\n$/,"");if(N.slice(0,4)!=="<!--")return!1;var X=N.indexOf("-->");if(X!==-1&&!/^\s*$/.test(N.slice(X+3)))return!1;var wt=X===-1?N.slice(4):N.slice(4,X),M=wt.split(`
`);if(M.length===1){var at=M[0].trim();h(d()+(at?"# "+at:"#")),g()}else h(d()+"#+BEGIN_COMMENT"),g(),M.forEach(function(gt,mt){(mt===0||mt===M.length-1)&&gt.trim()===""||(h(d()+b.protectBlockBody(gt)),g())}),h(d()+"#+END_COMMENT"),g();return!0}for(var Nt=f.walker(),O,c,pt;O=Nt.next();)switch(c=O.node,pt=c.type,pt){case"text":Y===0&&yt(c.literal,c);break;case"softbreak":if(U){h(" ");break}g(),h(d()),
_=!0;break;case"linebreak":h("\\\\"),g(),h(d()),_=!0;break;case"code":et&&c.literal.indexOf("|")!==-1?h(b.escapeCell(c.literal)):h(b.codeSpan(c.literal));break;case"emph":h("/");break;case"footnote_definition":O.entering?(j(),c.prev&&c.prev.type==="footnote_definition"?H():A(c),h(d()+"[fn:"+J(c._label)+"] "),U=!0):(U=!1,v=v.replace(/[ \t]+$/,""),g(),H(),P(c));break;case"footnote_reference":h(J(c._label)?
"[fn:"+J(c._label)+"]":"[^"+c._label+"]");break;case"table":O.entering?(j(),A(c)):P(c);break;case"table_row":if(O.entering)h(d()+"|");else if(g(),c._isHeading){for(var ft=[],dt=[],_t=!1,T=c.firstChild;T;)ft.push("----"),dt.push(T._align==="center"?" <c> ":T._align==="right"?" <r> ":T._align==="left"?" <l> ":" "),T._align&&(_t=!0),T=T.next;h(d()+"|"+ft.join("+")+"|"),g(),_t&&(h(d()+"|"+dt.join("|")+
"|"),g())}break;case"table_cell":et=O.entering,O.entering?h(" "):h(" |");break;case"strikethrough":h("+");break;case"strong":h("*");break;case"link":case"image":O.entering?(R>0?(h(b.escapeLinkPath(c.destination)),Y++):c.destination&&!c.firstChild?(h("[["+b.escapeLinkPath(c.destination)),m++):c.destination?h("[["+b.escapeLinkPath(c.destination)+"]["):D++,R++):(R--,R>0?Y--:D?D--:m?(m--,h("]]")):Lt());
break;case"html_inline":h("@@html:"+c.literal+"@@");break;case"html_block":j(),A(c),ut(c.literal)||(h(d()+"#+BEGIN_EXPORT html"),g(),rt(b.protectBlockBody(c.literal)),h(d()+"#+END_EXPORT"),g()),P(c);break;case"paragraph":O.entering?(U||A(c),v===""&&(v+=d()),_=!0,V=!0):(U?h(" "):g(),V=!1,P(c));break;case"heading":O.entering?(it=nt||S.length,it?(S.length||A(c),v===""&&(v+=d()),h("*")):(j(),A(c),h("*".
repeat(c.level)+" "))):(it&&(v.slice(-1)==="*"?v=v.slice(0,-1):h("*")),g(),P(c));break;case"code_block":j(),A(c);var st=(c.info||"").trim().split(/[\s{}]+/).filter(Boolean)[0]||"";h(d()+(st?"#+BEGIN_SRC "+st:"#+BEGIN_EXAMPLE")),g(),rt(b.protectBlockBody(c.literal)),h(d()+(st?"#+END_SRC":"#+END_EXAMPLE")),g(),P(c);break;case"thematic_break":j(),A(c),h(d()+"-----"),g(),P(c);break;case"block_quote":O.
entering?(j(),A(c),h(d()+"#+BEGIN_QUOTE"),g(),nt++,c.sourcepos&&(tt=c.sourcepos[0][0])):(nt--,j(),h(d()+"#+END_QUOTE"),g(),P(c));break;case"list":O.entering?(S.length||A(c),S.push({ordered:c.listType==="ordered",n:c.listStart===null||c.listStart===void 0?1:c.listStart,first:!0})):(S.pop(),P(c));break;case"item":if(O.entering){j();var $=S[S.length-1],G;$.ordered?(G=$.n+". ",$.first&&$.n!==1&&(G+="[\
@"+$.n+"] "),$.n++):G="- ",$.first=!1,v+=d()+G,Q.push(" ".repeat(G.length)),_=!0}else Q.pop();break;default:break}for(v!==""&&g();L.length&&L[0]==="";)L.shift();for(;L.length&&L[L.length-1]==="";)L.pop();return L.join(`
`)}function md2org(f){if(typeof f!="string"&&(f=String(f??"")),f==="")return"";renderOrg.warn=[];var b=new __cmark.Parser({sourcepos:!0}),B={codeSpan,escapeLinkDesc,escapeLinkPath,protectBlockBody,escapeCell},q=renderOrg(b.parse(f),B);return renderOrg.warn.length?q+`

# md2org warnings:
`+renderOrg.warn.map(function(K){return"# line "+K.n+": "+K.t}).join(`
`):q}

try{var i=$text==null?"":String($text);if(i=="")return "⚠️ md2org: no input — set the Text field to Clipboard";var o=md2org(i);return o==""?"⚠️ md2org: result was empty":o}catch(e){return "⚠️ md2org: "+(e&&e.message||e)}
