// transform.js, md2org 1.1.0
var __cmark=(()=>{var f=Object.create,v=Object.defineProperty,H=Object.getOwnPropertyDescriptor,W=Object.getOwnPropertyNames,it=Object.getPrototypeOf,U=Object.prototype.hasOwnProperty,z=(t,e,n)=>()=>{if(n)throw n[0];try{return t&&(e=t(t=0)),e}catch(i){throw n=[i],i}},F=(t,e)=>()=>{try{return e||t((e={exports:{}}).exports,e),e.exports}catch(n){throw e=0,n}},xt=(t,e)=>{for(var n in e)v(t,n,{get:e[n],
enumerable:!0})},rt=(t,e,n,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let r of W(e))!U.call(t,r)&&r!==n&&v(t,r,{get:()=>e[r],enumerable:!(i=H(e,r))||i.enumerable});return t},N=(t,e,n)=>(n=t!=null?f(it(t)):{},rt(e||!t||!t.__esModule?v(n,"default",{value:t,enumerable:!0}):n,t)),g=t=>rt(v({},"__esModule",{value:!0}),t);function st(t){switch(t._type){case"document":case"block_quote":case"\
list":case"item":case"paragraph":case"heading":case"emph":case"strong":case"strikethrough":case"table":case"table_row":case"table_cell":case"footnote_definition":case"link":case"image":case"custom_inline":case"custom_block":return!0;default:return!1}}var $,I,at,D,m,_,yt=z(()=>{"use strict";$=function(t,e){this.current=t,this.entering=e===!0},I=function(){var t=this.current,e=this.entering;if(t===null)
return null;var n=st(t);return e&&n?t._firstChild?(this.current=t._firstChild,this.entering=!0):this.entering=!1:t===this.root?this.current=null:t._next===null?(this.current=t._parent,this.entering=!1):(this.current=t._next,this.entering=!0),{entering:e,node:t}},at=function(t){return{current:t,root:t,entering:!0,next:I,resumeAt:$}},D=function(t,e){this._type=t,this._parent=null,this._firstChild=null,
this._lastChild=null,this._prev=null,this._next=null,this._sourcepos=e,this._open=!0,this._string_content=null,this._literal=null,this._listData={},this._info=null,this._destination=null,this._title=null,this._isFenced=!1,this._fenceChar=null,this._fenceLength=0,this._fenceOffset=null,this._level=null,this._onEnter=null,this._onExit=null},m=D.prototype,Object.defineProperty(m,"isContainer",{get:function(){
return st(this)}}),Object.defineProperty(m,"type",{get:function(){return this._type}}),Object.defineProperty(m,"firstChild",{get:function(){return this._firstChild}}),Object.defineProperty(m,"lastChild",{get:function(){return this._lastChild}}),Object.defineProperty(m,"next",{get:function(){return this._next}}),Object.defineProperty(m,"prev",{get:function(){return this._prev}}),Object.defineProperty(
m,"parent",{get:function(){return this._parent}}),Object.defineProperty(m,"sourcepos",{get:function(){return this._sourcepos}}),Object.defineProperty(m,"literal",{get:function(){return this._literal},set:function(t){this._literal=t}}),Object.defineProperty(m,"destination",{get:function(){return this._destination},set:function(t){this._destination=t}}),Object.defineProperty(m,"title",{get:function(){
return this._title},set:function(t){this._title=t}}),Object.defineProperty(m,"info",{get:function(){return this._info},set:function(t){this._info=t}}),Object.defineProperty(m,"level",{get:function(){return this._level},set:function(t){this._level=t}}),Object.defineProperty(m,"listType",{get:function(){return this._listData.type},set:function(t){this._listData.type=t}}),Object.defineProperty(m,"lis\
tTight",{get:function(){return this._listData.tight},set:function(t){this._listData.tight=t}}),Object.defineProperty(m,"listStart",{get:function(){return this._listData.start},set:function(t){this._listData.start=t}}),Object.defineProperty(m,"listDelimiter",{get:function(){return this._listData.delimiter},set:function(t){this._listData.delimiter=t}}),Object.defineProperty(m,"onEnter",{get:function(){
return this._onEnter},set:function(t){this._onEnter=t}}),Object.defineProperty(m,"onExit",{get:function(){return this._onExit},set:function(t){this._onExit=t}}),D.prototype.appendChild=function(t){t.unlink(),t._parent=this,this._lastChild?(this._lastChild._next=t,t._prev=this._lastChild,this._lastChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.prependChild=function(t){t.unlink(),t._parent=
this,this._firstChild?(this._firstChild._prev=t,t._next=this._firstChild,this._firstChild=t):(this._firstChild=t,this._lastChild=t)},D.prototype.unlink=function(){this._prev?this._prev._next=this._next:this._parent&&(this._parent._firstChild=this._next),this._next?this._next._prev=this._prev:this._parent&&(this._parent._lastChild=this._prev),this._parent=null,this._next=null,this._prev=null},D.prototype.
insertAfter=function(t){t.unlink(),t._next=this._next,t._next&&(t._next._prev=t),t._prev=this,this._next=t,t._parent=this._parent,t._next||(t._parent._lastChild=t)},D.prototype.insertBefore=function(t){t.unlink(),t._prev=this._prev,t._prev&&(t._prev._next=t),t._next=this,this._prev=t,t._parent=this._parent,t._prev||(t._parent._firstChild=t)},D.prototype.walker=function(){var t=new at(this);return t},
_=D}),lt=F((t,e)=>{"use strict";var n={};function i(s){var l,a,o=n[s];if(o)return o;for(o=n[s]=[],l=0;l<128;l++)a=String.fromCharCode(l),/^[0-9a-z]$/i.test(a)?o.push(a):o.push("%"+("0"+l.toString(16).toUpperCase()).slice(-2));for(l=0;l<s.length;l++)o[s.charCodeAt(l)]=s[l];return o}function r(s,l,a){var o,u,d,L,C,y="";for(typeof l!="string"&&(a=l,l=r.defaultChars),typeof a>"u"&&(a=!0),C=i(l),o=0,u=
s.length;o<u;o++){if(d=s.charCodeAt(o),a&&d===37&&o+2<u&&/^[0-9a-f]{2}$/i.test(s.slice(o+1,o+3))){y+=s.slice(o,o+3),o+=2;continue}if(d<128){y+=C[d];continue}if(d>=55296&&d<=57343){if(d>=55296&&d<=56319&&o+1<u&&(L=s.charCodeAt(o+1),L>=56320&&L<=57343)){y+=encodeURIComponent(s[o]+s[o+1]),o++;continue}y+="%EF%BF%BD";continue}y+=encodeURIComponent(s[o])}return y}r.defaultChars=";/?:@&=+$,-_.!~*'()#",r.
componentChars="-_.!~*'()",e.exports=r}),ot=F((t,e)=>{function n(i){return i}e.exports={decodeHTML:n,decodeHTMLStrict:n,encodeHTML:i=>i,escape:i=>i.replace(/[&<>"]/g,r=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[r])}}),q,ct,ht,Y,G,V,ut,pt,ft,tt,Z,x,dt,h,b,A,et,B,E,jt,At,_t,Et,Pt,O,c,gt,X,Q=z(()=>{"use strict";q=N(lt(),1),ct=N(ot(),1),ht=92,Y="&(?:#x[a-f0-9]{1,6}|#[0-9]{1,7}|[a-z][a-z0-9]{1\
,31});",G="[A-Za-z][A-Za-z0-9-]*",V="[a-zA-Z_:][a-zA-Z0-9:._-]*",ut="[^\"'=<>`\\x00-\\x20]+",pt="'[^']*'",ft='"[^"]*"',tt="(?:"+ut+"|"+pt+"|"+ft+")",Z="(?:\\s*=\\s*"+tt+")",x="(?:\\s+"+V+Z+"?)",dt="<"+G+x+"*\\s*/?>",h="</"+G+"\\s*[>]",b="<!-->|<!--->|<!--[\\s\\S]*?-->",A="[<][?][\\s\\S]*?[?][>]",et="<![A-Za-z]+[^>]*>",B="<!\\[CDATA\\[[\\s\\S]*?\\]\\]>",E="(?:"+dt+"|"+h+"|"+b+"|"+A+"|"+et+"|"+B+")",
jt=new RegExp("^"+E),At=/[\\&]/,_t="[!\"#$%&'()*+,./:;<=>?@[\\\\\\]^_`{|}~-]",Et=new RegExp("\\\\"+_t+"|"+Y,"gi"),Pt='[&<>"]',O=new RegExp(Pt,"g"),c=function(t){return t.charCodeAt(0)===ht?t.charAt(1):(0,ct.decodeHTMLStrict)(t)},gt=function(t){return At.test(t)?t.replace(Et,c):t},X=function(t){try{return(0,q.default)(t)}catch{return t}}});function nt(t){return mt(t)}var mt,Lt,Nt,M=z(()=>{"use stri\
ct";String.fromCodePoint?mt=function(t){try{return String.fromCodePoint(t)}catch(e){if(e instanceof RangeError)return"\uFFFD";throw e}}:(Lt=String.fromCharCode,Nt=Math.floor,mt=function(){var t=16384,e=[],n,i,r=-1,s=arguments.length;if(!s)return"";for(var l="";++r<s;){var a=Number(arguments[r]);if(!isFinite(a)||a<0||a>1114111||Nt(a)!==a)return"\uFFFD";a<=65535?e.push(a):(a-=65536,n=(a>>10)+55296,i=
a%1024+56320,e.push(n,i)),(r+1===s||e.length>t)&&(l+=Lt.apply(null,e),e.length=0)}return l})});function wt(t){return{subject:"",delimiters:null,brackets:null,pos:0,refmap:{},match:ye,peek:Le,spnl:Ne,parseBackticks:we,parseBackslash:Oe,parseAutolink:De,parseHtmlTag:Be,scanDelims:je,handleDelim:Ae,parseLinkTitle:ze,parseLinkDestination:$e,parseLinkLabel:Te,parseOpenBracket:Se,parseBang:Re,parseCloseBracket:Ue,
addBracket:Fe,removeBracket:Ze,parseEntity:Me,parseString:He,parseNewline:Ie,parseReference:qe,parseInline:Ge,processEmphasis:Pe,removeDelimiter:Ee,options:t||{},parse:Xe}}var S,T,p,k,P,R,zt,vt,ie,Rt,re,Ut,se,Ft,$t,ae,K,J,Tt,Zt,St,le,oe,Mt,ce,he,Ht,ue,pe,fe,de,_e,ge,me,ve,It,qt,ke,be,Gt,Ce,xe,w,Xt,ye,Le,Ne,we,Oe,De,Be,je,Ae,Ee,Qt,Pe,ze,$e,Te,Se,Re,Ue,Fe,Ze,Me,He,Ie,qe,Ge,Xe,Qe,jn=z(()=>{"use stric\
t";yt(),Q(),M(),S=N(ot(),1),T=X,p=gt,k=10,P=42,R=95,zt=96,vt=91,ie=93,Rt=60,re=33,Ut=92,se=38,Ft=40,$t=41,ae=58,K=39,J=34,Tt=126,Zt=_t,St="\\\\"+Zt,le=Y,oe=jt,Mt=new RegExp(/^[!"#$%&'()*+,\-./:;<=>?@\[\]\\^_`{|}~\p{P}\p{S}]/u),ce=new RegExp('^(?:"('+St+`|\\\\[^\\\\]|[^\\\\"\\x00])*"|'(`+St+"|\\\\[^\\\\]|[^\\\\'\\x00])*'|\\(("+St+"|\\\\[^\\\\]|[^\\\\()\\x00])*\\))"),he=/^(?:<(?:[^<>\n\\\x00]|\\.)*>)/,
Ht=new RegExp("^"+Zt),ue=new RegExp("^"+le,"i"),pe=/`+/,fe=/^`+/,de=/\.\.\./g,_e=/--+/g,ge=/^<([a-zA-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*)>/,me=/^<[A-Za-z][A-Za-z0-9.+-]{1,31}:[^<>\x00-\x20]*>/i,ve=/^ *(?:\n *)?/,It=/^[ \t\n\x0b\x0c\x0d]/,qt=/^\s/,ke=/ *$/,be=/^ */,Gt=/^ *(?:\n|$)/,Ce=/^\[(?:[^\\\[\]]|\\.){0,1000}\]/s,
xe=/^[^\n`\[\]\\!<&*_'"~]+/m,w=function(t){var e=new _("text");return e._literal=t,e},Xt=function(t){return t.slice(1,t.length-1).trim().replace(/[ \t\r\n]+/g," ").toLowerCase().toUpperCase()},ye=function(t){var e=t.exec(this.subject.slice(this.pos));return e===null?null:(this.pos+=e.index+e[0].length,e[0])},Le=function(){return this.pos<this.subject.length?this.subject.charCodeAt(this.pos):-1},Ne=
function(){return this.match(ve),!0},we=function(t){var e=this.match(fe);if(e===null)return!1;for(var n=this.pos,i,r,s;(i=this.match(pe))!==null;)if(i===e)return r=new _("code"),s=this.subject.slice(n,this.pos-e.length).replace(/\n/gm," "),s.length>0&&s.match(/[^ ]/)!==null&&s[0]==" "&&s[s.length-1]==" "?r._literal=s.slice(1,s.length-1):r._literal=s,t.appendChild(r),!0;return this.pos=n,t.appendChild(
w(e)),!0},Oe=function(t){var e=this.subject,n;return this.pos+=1,this.peek()===k?(this.pos+=1,n=new _("linebreak"),t.appendChild(n)):Ht.test(e.charAt(this.pos))?(t.appendChild(w(e.charAt(this.pos))),this.pos+=1):t.appendChild(w("\\")),!0},De=function(t){var e,n,i;return(e=this.match(ge))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=T("mailto:"+n),i._title="",i.appendChild(w(n)),t.appendChild(
i),!0):(e=this.match(me))?(n=e.slice(1,e.length-1),i=new _("link"),i._destination=T(n),i._title="",i.appendChild(w(n)),t.appendChild(i),!0):!1},Be=function(t){var e=this.match(oe);if(e===null)return!1;var n=new _("html_inline");return n._literal=e,t.appendChild(n),!0},je=function(t){var e=0,n,i,r,s=this.pos,l,a,o,u,d,L,C,y;if(t===K||t===J)e++,this.pos++;else for(;this.peek()===t;)e++,this.pos++;return e===
0?null:(n=s===0?`
`:this.subject.charAt(s-1),r=this.peek(),r===-1?i=`
`:i=nt(r),d=qt.test(i),L=Mt.test(i),C=qt.test(n),y=Mt.test(n),l=!d&&(!L||C||y),a=!C&&(!y||d||L),t===R?(o=l&&(!a||y),u=a&&(!l||L)):t===K||t===J?(o=l&&!a,u=a):(o=l,u=a),this.pos=s,{numdelims:e,can_open:o,can_close:u})},Ae=function(t,e){var n=this.scanDelims(t);if(!n)return!1;var i=n.numdelims,r=this.pos,s;this.pos+=i,t===K?s="\u2019":t===J?s="\u201C":s=this.subject.slice(r,this.pos);var l=w(s);return e.
appendChild(l),(n.can_open||n.can_close)&&(this.options.smart||t!==K&&t!==J)&&(this.delimiters={cc:t,numdelims:i,origdelims:i,node:l,previous:this.delimiters,next:null,can_open:n.can_open,can_close:n.can_close},this.delimiters.previous!==null&&(this.delimiters.previous.next=this.delimiters)),!0},Ee=function(t){t.previous!==null&&(t.previous.next=t.next),t.next===null?this.delimiters=t.previous:t.next.
previous=t.previous},Qt=function(t,e){t.next!==e&&(t.next=e,e.previous=t)},Pe=function(t){for(var e,n,i,r,s,l,a,o,u,d,L=[],C,y=!1,bt=0;bt<14;bt++)L[bt]=t;for(n=this.delimiters;n!==null&&n.previous!==t;)n=n.previous;for(;n!==null;){var Ct=n.cc;if(!n.can_close)n=n.next;else{switch(e=n.previous,d=!1,Ct){case K:C=0;break;case J:C=1;break;case R:C=2+(n.can_open?3:0)+n.origdelims%3;break;case P:C=8+(n.can_open?
3:0)+n.origdelims%3;break;case Tt:C=14;break}for(;e!==null&&e!==t&&e!==L[C];){if(y=(n.can_open||e.can_close)&&n.origdelims%3!==0&&(e.origdelims+n.origdelims)%3===0,e.cc===n.cc&&e.can_open&&!y){d=!0;break}e=e.previous}if(i=n,Ct===Tt)if(!d||n.numdelims<2||e.numdelims<2)n=n.next;else{r=e.node,s=n.node,e.numdelims-=2,n.numdelims-=2,r._literal=r._literal.slice(0,r._literal.length-2),s._literal=s._literal.
slice(0,s._literal.length-2);for(var Dn=new _("strikethrough"),Bt=r._next;Bt&&Bt!==s;){var zn=Bt._next;Dn.appendChild(Bt),Bt=zn}r.insertAfter(Dn),Qt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else if(Ct===P||Ct===R)if(!d)n=n.next;else{a=n.numdelims>=2&&e.numdelims>=2?2:1,r=e.node,s=n.node,e.numdelims-=a,n.numdelims-=
a,r._literal=r._literal.slice(0,r._literal.length-a),s._literal=s._literal.slice(0,s._literal.length-a);var Bn=new _(a===1?"emph":"strong");for(o=r._next;o&&o!==s;)u=o._next,o.unlink(),Bn.appendChild(o),o=u;r.insertAfter(Bn),Qt(e,n),e.numdelims===0&&(r.unlink(),this.removeDelimiter(e)),n.numdelims===0&&(s.unlink(),l=n.next,this.removeDelimiter(n),n=l)}else Ct===K?(n.node._literal="\u2019",d&&(e.node.
_literal="\u2018"),n=n.next):Ct===J&&(n.node._literal="\u201D",d&&(e.node.literal="\u201C"),n=n.next);d||(L[C]=i.previous,i.can_open||this.removeDelimiter(i))}}for(;this.delimiters!==null&&this.delimiters!==t;)this.removeDelimiter(this.delimiters)},ze=function(){var t=this.match(ce);return t===null?null:p(t.slice(1,-1))},$e=function(){var t=this.match(he);if(t===null){if(this.peek()===Rt)return null;
for(var e=this.pos,n=0,i;(i=this.peek())!==-1;)if(i===Ut&&Ht.test(this.subject.charAt(this.pos+1)))this.pos+=1,this.peek()!==-1&&(this.pos+=1);else if(i===Ft)this.pos+=1,n+=1;else if(i===$t){if(n<1)break;this.pos+=1,n-=1}else{if(It.exec(nt(i))!==null)break;this.pos+=1}return this.pos===e&&i!==$t||n!==0?null:(t=this.subject.slice(e,this.pos),T(p(t)))}else return T(p(t.slice(1,-1)))},Te=function(){var t=this.
match(Ce);return t===null||t.length>1001?0:t.length},Se=function(t){var e=this.pos,n=this.match(/^\[\^[^\]]+\]/);if(n){var i=new _("footnote_reference");return i._label=n.slice(2,-1),t.appendChild(i),!0}this.pos+=1;var r=w("[");return t.appendChild(r),this.addBracket(r,e,!1),!0},Re=function(t){var e=this.pos;if(this.pos+=1,this.peek()===vt){this.pos+=1;var n=w("![");t.appendChild(n),this.addBracket(
n,e+1,!0)}else t.appendChild(w("!"));return!0},Ue=function(t){var e,n,i,r,s=!1,l,a;if(this.pos+=1,e=this.pos,a=this.brackets,a===null)return t.appendChild(w("]")),!0;if(!a.active)return t.appendChild(w("]")),this.removeBracket(),!0;n=a.image;var o=this.pos;if(this.peek()===Ft&&(this.pos++,this.spnl()&&(i=this.parseLinkDestination())!==null&&this.spnl()&&(It.test(this.subject.charAt(this.pos-1))&&(r=
this.parseLinkTitle())||!0)&&this.spnl()&&this.peek()===$t?(this.pos+=1,s=!0):this.pos=o),!s){var u=this.pos,d=this.parseLinkLabel();if(d>2?l=this.subject.slice(u,u+d):a.bracketAfter||(l=this.subject.slice(a.index,e)),d===0&&(this.pos=o),l){var L=this.refmap[Xt(l)];L&&(i=L.destination,r=L.title,s=!0)}}if(s){var C=new _(n?"image":"link");C._destination=i,C._title=r||"";var y,bt;for(y=a.node._next;y;)
bt=y._next,y.unlink(),C.appendChild(y),y=bt;if(t.appendChild(C),this.processEmphasis(a.previousDelimiter),this.removeBracket(),a.node.unlink(),!n)for(a=this.brackets;a!==null;)a.image||(a.active=!1),a=a.previous;return!0}else return this.removeBracket(),this.pos=e,t.appendChild(w("]")),!0},Fe=function(t,e,n){this.brackets!==null&&(this.brackets.bracketAfter=!0),this.brackets={node:t,previous:this.
brackets,previousDelimiter:this.delimiters,index:e,image:n,active:!0}},Ze=function(){this.brackets=this.brackets.previous},Me=function(t){var e;return(e=this.match(ue))?(t.appendChild(w((0,S.decodeHTMLStrict)(e))),!0):!1},He=function(t){var e;return(e=this.match(xe))?(this.options.smart?t.appendChild(w(e.replace(de,"\u2026").replace(_e,function(n){var i=0,r=0;return n.length%3===0?r=n.length/3:n.length%
2===0?i=n.length/2:n.length%3===2?(i=1,r=(n.length-2)/3):(i=2,r=(n.length-4)/3),"\u2014".repeat(r)+"\u2013".repeat(i)}))):t.appendChild(w(e)),!0):!1},Ie=function(t){this.pos+=1;var e=t._lastChild;if(e&&e.type==="text"&&e._literal[e._literal.length-1]===" "){var n=e._literal[e._literal.length-2]===" ";e._literal=e._literal.replace(ke,""),t.appendChild(new _(n?"linebreak":"softbreak"))}else t.appendChild(
new _("softbreak"));return this.match(be),!0},qe=function(t,e){this.subject=t,this.pos=0;var n,i,r,s,l=this.pos;if(s=this.parseLinkLabel(),s===0)return 0;if(n=this.subject.slice(0,s),this.peek()===ae)this.pos++;else return this.pos=l,0;if(this.spnl(),i=this.parseLinkDestination(),i===null)return this.pos=l,0;var a=this.pos;this.spnl(),this.pos!==a&&(r=this.parseLinkTitle()),r===null&&(this.pos=a);
var o=!0;if(this.match(Gt)===null&&(r===null?o=!1:(r=null,this.pos=a,o=this.match(Gt)!==null)),!o)return this.pos=l,0;var u=Xt(n);return u===""?(this.pos=l,0):(e[u]||(e[u]={destination:i,title:r===null?"":r}),this.pos-l)},Ge=function(t){var e=!1,n=this.peek();if(n===-1)return!1;switch(n){case k:e=this.parseNewline(t);break;case Ut:e=this.parseBackslash(t);break;case zt:e=this.parseBackticks(t);break;case P:case R:case Tt:
e=this.handleDelim(n,t);break;case K:case J:e=this.options.smart&&this.handleDelim(n,t);break;case vt:e=this.parseOpenBracket(t);break;case re:e=this.parseBang(t);break;case ie:e=this.parseCloseBracket(t);break;case Rt:e=this.parseAutolink(t)||this.parseHtmlTag(t);break;case se:e=this.parseEntity(t);break;default:e=this.parseString(t);break}return e||(this.pos+=1,t.appendChild(w(nt(n)))),!0},Xe=function(t){
for(this.subject=t._string_content.trim(),this.pos=0,this.delimiters=null,this.brackets=null;this.parseInline(t););t._string_content=null,this.processEmphasis(null)},Qe=wt}),Ke={};xt(Ke,{default:()=>On});function An(t){return{doc:new ne,blocks:ee,blockStarts:kn,tip:this.doc,oldtip:this.doc,currentLine:"",lineNumber:0,offset:0,column:0,nextNonspace:0,nextNonspaceColumn:0,indent:0,indented:!1,blank:!1,
partiallyConsumedTab:!1,allClosed:!0,lastMatchedContainer:this.doc,refmap:{},lastLineLength:0,inlineParser:new Qe(t),findNextNonspace:xn,advanceOffset:bn,advanceNextNonspace:Cn,addLine:fn,addChild:dn,incorporateLine:yn,finalize:Ln,processInlines:Nn,closeUnmatchedBlocks:mn,parse:wn,options:t||{}}}var Ot,Kt,Je,Jt,We,Wt,Yt,Ye,Ve,tn,en,nn,Dt,rn,Vt,sn,an,ln,on,cn,hn,un,pn,kt,j,te,fn,dn,_n,gn,mn,vn,ee,kn,
bn,Cn,xn,yn,Ln,Nn,ne,wn,On,En=z(()=>{"use strict";yt(),Q(),jn(),Ot=4,Kt=9,Je=10,Jt=62,We=60,Wt=32,Yt=91,Ye=[/./,/^<(?:script|pre|textarea|style)(?:\s|>|$)/i,/^<!--/,/^<[?]/,/^<![A-Za-z]/,/^<!\[CDATA\[/,/^<[/]?(?:address|article|aside|base|basefont|blockquote|body|caption|center|col|colgroup|dd|details|dialog|dir|div|dl|dt|fieldset|figcaption|figure|footer|form|frame|frameset|h[123456]|head|header|hr|html|iframe|legend|li|link|main|menu|menuitem|nav|noframes|ol|optgroup|option|p|param|section|search|summary|table|tbody|td|tfoot|th|thead|title|tr|track|ul)(?:\s|[/]?[>]|$)/i,
new RegExp("^(?:"+dt+"|"+h+")\\s*$","i")],Ve=[/./,/<\/(?:script|pre|textarea|style)>/i,/-->/,/\?>/,/>/,/\]\]>/],tn=/^(?:\*[ \t]*){3,}$|^(?:_[ \t]*){3,}$|^(?:-[ \t]*){3,}$/,en=/^\[\^([^\]]+)\]:[ \t]*/,nn=/^\|?[ \t]*:?-+:?[ \t]*(?:\|[ \t]*:?-+:?[ \t]*)*\|?[ \t]*$/,Dt=function(t){var e=[],n="",i,r;for(t=t.trim().replace(/^\|/,"").replace(/\|[ \t]*$/,""),i=0;i<t.length;i++)r=t.charAt(i),r==="\\"&&t.charAt(
i+1)==="|"?(n+="|",i++):r==="|"?(e.push(n.trim()),n=""):n+=r;return e.push(n.trim()),e},rn=/^[#`~*+_=<>0-9|:[-]/,Vt=/[^ \t\f\v\r\n]/,sn=/^[*+-]/,an=/^(\d{1,9})([.)])/,ln=/^#{1,6}(?:[ \t]+|$)/,on=/^`{3,}(?!.*`)|^~{3,}/,cn=/^(?:`{3,}|~{3,})(?=[ \t]*$)/,hn=/^(?:=+|-+)[ \t]*$/,un=/\r\n|\n|\r/,pn=function(t){return!Vt.test(t)},kt=function(t){return t===Wt||t===Kt},j=function(t,e){return e<t.length?t.charCodeAt(
e):-1},te=function(t){return t.next&&t.sourcepos[1][0]!==t.next.sourcepos[0][0]-1},fn=function(){if(this.partiallyConsumedTab){this.offset+=1;var t=4-this.column%4;this.tip._string_content+=" ".repeat(t)}this.tip._string_content+=this.currentLine.slice(this.offset)+`
`},dn=function(t,e){for(;!this.blocks[this.tip.type].canContain(t);)this.finalize(this.tip,this.lineNumber-1);var n=e+1,i=new _(t,[[this.lineNumber,n],[0,0]]);return i._string_content="",this.tip.appendChild(i),this.tip=i,i},_n=function(t,e){var n=t.currentLine.slice(t.nextNonspace),i,r,s,l,a={type:null,tight:!0,bulletChar:null,start:null,delimiter:null,padding:null,markerOffset:t.indent};if(t.indent>=
4)return null;if(i=n.match(sn))a.type="bullet",a.bulletChar=i[0][0];else if((i=n.match(an))&&(e.type!=="paragraph"||i[1]==1))a.type="ordered",a.start=parseInt(i[1]),a.delimiter=i[2];else return null;if(r=j(t.currentLine,t.nextNonspace+i[0].length),!(r===-1||r===Kt||r===Wt)||e.type==="paragraph"&&!t.currentLine.slice(t.nextNonspace+i[0].length).match(Vt))return null;t.advanceNextNonspace(),t.advanceOffset(
i[0].length,!0),s=t.column,l=t.offset;do t.advanceOffset(1,!0),r=j(t.currentLine,t.offset);while(t.column-s<5&&kt(r));var o=j(t.currentLine,t.offset)===-1,u=t.column-s;return u>=5||u<1||o?(a.padding=i[0].length+1,t.column=s,t.offset=l,kt(j(t.currentLine,t.offset))&&t.advanceOffset(1,!0)):a.padding=i[0].length+u,a},gn=function(t,e){return t.type===e.type&&t.delimiter===e.delimiter&&t.bulletChar===e.
bulletChar},mn=function(){if(!this.allClosed){for(;this.oldtip!==this.lastMatchedContainer;){var t=this.oldtip._parent;this.finalize(this.oldtip,this.lineNumber-1),this.oldtip=t}this.allClosed=!0}},vn=function(t,e){for(var n,i,r=e.walker(),s=[];n=r.next();)if(i=n.node,n.entering&&i.type==="paragraph"){for(var l,a=!1;j(i._string_content,0)===Yt&&(l=t.inlineParser.parseReference(i._string_content,t.
refmap));){let o=i._string_content.slice(0,l);i._string_content=i._string_content.slice(l),a=!0;let u=o.split(`
`);i.sourcepos[0][0]+=u.length-1}a&&pn(i._string_content)&&s.push(i)}for(i of s)i.unlink()},ee={document:{continue:function(){return 0},finalize:function(t,e){vn(t,e)},canContain:function(t){return t!=="item"},acceptsLines:!1},list:{continue:function(){return 0},finalize:function(t,e){for(var n=e._firstChild;n;){if(n._next&&te(n)){e._listData.tight=!1;break}for(var i=n._firstChild;i;){if(i._next&&
te(i)){e._listData.tight=!1;break}i=i._next}n=n._next}e.sourcepos[1]=e._lastChild.sourcepos[1]},canContain:function(t){return t==="item"},acceptsLines:!1},block_quote:{continue:function(t){var e=t.currentLine;if(!t.indented&&j(e,t.nextNonspace)===Jt)t.advanceNextNonspace(),t.advanceOffset(1,!1),kt(j(e,t.offset))&&t.advanceOffset(1,!0);else return 1;return 0},finalize:function(){},canContain:function(t){
return t!=="item"},acceptsLines:!1},item:{continue:function(t,e){if(t.blank){if(e._firstChild==null)return 1;t.advanceNextNonspace()}else if(t.indent>=e._listData.markerOffset+e._listData.padding)t.advanceOffset(e._listData.markerOffset+e._listData.padding,!0);else return 1;return 0},finalize:function(t,e){e._lastChild?e.sourcepos[1]=e._lastChild.sourcepos[1]:(e.sourcepos[1][0]=e.sourcepos[0][0],e.
sourcepos[1][1]=e._listData.markerOffset+e._listData.padding)},canContain:function(t){return t!=="item"},acceptsLines:!1},heading:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},thematic_break:{continue:function(){return 1},finalize:function(){},canContain:function(){return!1},acceptsLines:!1},code_block:{continue:function(t,e){var n=t.currentLine,
i=t.indent;if(e._isFenced){var r=i<=3&&n.charAt(t.nextNonspace)===e._fenceChar&&n.slice(t.nextNonspace).match(cn);if(r&&r[0].length>=e._fenceLength)return t.lastLineLength=t.offset+i+r[0].length,t.finalize(e,t.lineNumber),2;for(var s=e._fenceOffset;s>0&&kt(j(n,t.offset));)t.advanceOffset(1,!0),s--}else if(i>=Ot)t.advanceOffset(Ot,!0);else if(t.blank)t.advanceNextNonspace();else return 1;return 0},
finalize:function(t,e){if(e._isFenced){var n=e._string_content,i=n.indexOf(`
`),r=n.slice(0,i),s=n.slice(i+1);e.info=gt(r.trim()),e._literal=s}else{for(var l=e._string_content.split(`
`);/^[ \t]*$/.test(l[l.length-1]);)l.pop();e._literal=l.join(`
`)+`
`,e.sourcepos[1][0]=e.sourcepos[0][0]+l.length-1,e.sourcepos[1][1]=e.sourcepos[0][1]+l[l.length-1].length-1}e._string_content=null},canContain:function(){return!1},acceptsLines:!0},html_block:{continue:function(t,e){return t.blank&&(e._htmlBlockType===6||e._htmlBlockType===7)?1:0},finalize:function(t,e){e._literal=e._string_content.replace(/\n$/,""),e._string_content=null},canContain:function(){return!1},
acceptsLines:!0},footnote_definition:{continue:function(t){return t.blank?0:t.indent>=4?(t.advanceOffset(4,!0),0):t.tip.type==="paragraph"?0:1},finalize:function(){},canContain:function(t){return t!=="item"&&t!=="footnote_definition"},acceptsLines:!1},table:{continue:function(t){return t.blank?1:0},finalize:function(t,e){var n=e._string_content.replace(/\n$/,"").split(`
`),i=Dt(n[1]),r=i.map(function(d){var L=d.charAt(0)===":",C=d.charAt(d.length-1)===":";return L&&C?"center":C?"right":L?"left":null}),s,l,a,o,u;for(s=0;s<n.length;s++)if(s!==1){for(a=Dt(n[s]),o=new _("table_row"),o._isHeading=s===0,l=0;l<i.length;l++)u=new _("table_cell"),u._align=r[l],u._string_content=a[l]===void 0?"":a[l],o.appendChild(u);e.appendChild(o)}e._string_content=null},canContain:function(t){
return t==="table_row"},acceptsLines:!0},paragraph:{continue:function(t){return t.blank?1:0},finalize:function(){},canContain:function(){return!1},acceptsLines:!0}},kn=[function(t){if(t.indented)return 0;var e=t.currentLine.slice(t.nextNonspace).match(en);if(!e)return 0;t.closeUnmatchedBlocks(),t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1);var n=t.addChild("footnote_definition",t.nextNonspace);
return n._label=e[1],1},function(t,e){if(t.indented||e.type!=="paragraph")return 0;var n=t.currentLine.slice(t.nextNonspace);if(n.indexOf("|")===-1||!nn.test(n))return 0;var i=e._string_content.replace(/\n$/,"").split(`
`),r=i[i.length-1];if(!r||r.indexOf("|")===-1||Dt(r).length!==Dt(n).length)return 0;var s=i.slice(0,i.length-1).join(`
`);e._string_content=s===""?"":s+`
`,t.closeUnmatchedBlocks();var l=s==="",a=t.addChild("table",t.nextNonspace);return l&&e.unlink(),a._string_content=r+`
`,2},function(t){return!t.indented&&j(t.currentLine,t.nextNonspace)===Jt?(t.advanceNextNonspace(),t.advanceOffset(1,!1),kt(j(t.currentLine,t.offset))&&t.advanceOffset(1,!0),t.closeUnmatchedBlocks(),t.addChild("block_quote",t.nextNonspace),1):0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(ln))){t.advanceNextNonspace(),t.advanceOffset(e[0].length,!1),t.closeUnmatchedBlocks();
var n=t.addChild("heading",t.nextNonspace);return n.level=e[0].trim().length,n._string_content=t.currentLine.slice(t.offset).replace(/^[ \t]*#+[ \t]*$/,"").replace(/[ \t]+#+[ \t]*$/,""),t.advanceOffset(t.currentLine.length-t.offset),2}else return 0},function(t){var e;if(!t.indented&&(e=t.currentLine.slice(t.nextNonspace).match(on))){var n=e[0].length;t.closeUnmatchedBlocks();var i=t.addChild("code\
_block",t.nextNonspace);return i._isFenced=!0,i._fenceLength=n,i._fenceChar=e[0][0],i._fenceOffset=t.indent,t.advanceNextNonspace(),t.advanceOffset(n,!1),2}else return 0},function(t,e){if(!t.indented&&j(t.currentLine,t.nextNonspace)===We){var n=t.currentLine.slice(t.nextNonspace),i;for(i=1;i<=7;i++)if(Ye[i].test(n)&&(i<7||e.type!=="paragraph"&&!(!t.allClosed&&!t.blank&&t.tip.type==="paragraph"))){
t.closeUnmatchedBlocks();var r=t.addChild("html_block",t.offset);return r._htmlBlockType=i,2}}return 0},function(t,e){var n;if(!t.indented&&e.type==="paragraph"&&(n=t.currentLine.slice(t.nextNonspace).match(hn))){t.closeUnmatchedBlocks();for(var i;j(e._string_content,0)===Yt&&(i=t.inlineParser.parseReference(e._string_content,t.refmap));)e._string_content=e._string_content.slice(i);if(e._string_content.
length>0){var r=new _("heading",e.sourcepos);return r.level=n[0][0]==="="?1:2,r._string_content=e._string_content,e.insertAfter(r),e.unlink(),t.tip=r,t.advanceOffset(t.currentLine.length-t.offset,!1),2}else return 0}else return 0},function(t){return!t.indented&&tn.test(t.currentLine.slice(t.nextNonspace))?(t.closeUnmatchedBlocks(),t.addChild("thematic_break",t.nextNonspace),t.advanceOffset(t.currentLine.
length-t.offset,!1),2):0},function(t,e){var n;return(!t.indented||e.type==="list")&&(n=_n(t,e))?(t.closeUnmatchedBlocks(),(t.tip.type!=="list"||!gn(e._listData,n))&&(e=t.addChild("list",t.nextNonspace),e._listData=n),e=t.addChild("item",t.nextNonspace),e._listData=n,1):0},function(t){return t.indented&&t.tip.type!=="paragraph"&&!t.blank?(t.advanceOffset(Ot,!0),t.closeUnmatchedBlocks(),t.addChild("\
code_block",t.offset),2):0}],bn=function(t,e){for(var n=this.currentLine,i,r,s;t>0&&(s=n[this.offset]);)s==="	"?(i=4-this.column%4,e?(this.partiallyConsumedTab=i>t,r=i>t?t:i,this.column+=r,this.offset+=this.partiallyConsumedTab?0:1,t-=r):(this.partiallyConsumedTab=!1,this.column+=i,this.offset+=1,t-=1)):(this.partiallyConsumedTab=!1,this.offset+=1,this.column+=1,t-=1)},Cn=function(){this.offset=this.
nextNonspace,this.column=this.nextNonspaceColumn,this.partiallyConsumedTab=!1},xn=function(){for(var t=this.currentLine,e=this.offset,n=this.column,i;(i=t.charAt(e))!=="";)if(i===" ")e++,n++;else if(i==="	")e++,n+=4-n%4;else break;this.blank=i===`
`||i==="\r"||i==="",this.nextNonspace=e,this.nextNonspaceColumn=n,this.indent=this.nextNonspaceColumn-this.column,this.indented=this.indent>=Ot},yn=function(t){var e=!0,n,i=this.doc;this.oldtip=this.tip,this.offset=0,this.column=0,this.blank=!1,this.partiallyConsumedTab=!1,this.lineNumber+=1,t.indexOf("\0")!==-1&&(t=t.replace(/\0/g,"\uFFFD")),this.currentLine=t;for(var r;(r=i._lastChild)&&r._open;){
switch(i=r,this.findNextNonspace(),this.blocks[i.type].continue(this,i)){case 0:break;case 1:e=!1;break;case 2:return;default:throw"continue returned illegal value, must be 0, 1, or 2"}if(!e){i=i._parent;break}}this.allClosed=i===this.oldtip,this.lastMatchedContainer=i;for(var s=i.type!=="paragraph"&&i.type!=="table"&&ee[i.type].acceptsLines,l=this.blockStarts,a=l.length;!s;){if(this.findNextNonspace(),
!this.indented&&!rn.test(t.slice(this.nextNonspace))){this.advanceNextNonspace();break}for(var o=0;o<a;){var u=l[o](this,i);if(u===1){i=this.tip;break}else if(u===2){i=this.tip,s=!0;break}else o++}if(o===a){this.advanceNextNonspace();break}}!this.allClosed&&!this.blank&&this.tip.type==="paragraph"?this.addLine():(this.closeUnmatchedBlocks(),n=i.type,this.blocks[n].acceptsLines?(this.addLine(),n===
"html_block"&&i._htmlBlockType>=1&&i._htmlBlockType<=5&&Ve[i._htmlBlockType].test(this.currentLine.slice(this.offset))&&(this.lastLineLength=t.length,this.finalize(i,this.lineNumber))):this.offset<t.length&&!this.blank&&(i=this.addChild("paragraph",this.offset),this.advanceNextNonspace(),this.addLine())),this.lastLineLength=t.length},Ln=function(t,e){var n=t._parent;t._open=!1,t.sourcepos[1]=[e,this.
lastLineLength],this.blocks[t.type].finalize(this,t),this.tip=n},Nn=function(t){var e,n,i,r=t.walker();for(this.inlineParser.refmap=this.refmap,this.inlineParser.options=this.options;n=r.next();)e=n.node,i=e.type,!n.entering&&(i==="paragraph"||i==="heading"||i==="table_cell")&&this.inlineParser.parse(e)},ne=function(){var t=new _("document",[[1,1],[0,0]]);return t},wn=function(t){this.doc=new ne,this.
tip=this.doc,this.refmap={},this.lineNumber=0,this.lastLineLength=0,this.offset=0,this.column=0,this.lastMatchedContainer=this.doc,this.currentLine="",this.options.time&&console.time("preparing input");var e=t.split(un),n=e.length;t.charCodeAt(t.length-1)===Je&&(n-=1),this.options.time&&console.timeEnd("preparing input"),this.options.time&&console.time("block parsing");for(var i=0;i<n;i++)this.incorporateLine(
e[i]);for(;this.tip;)this.finalize(this.tip,n);return this.options.time&&console.timeEnd("block parsing"),this.options.time&&console.time("inline parsing"),this.processInlines(this.doc),this.options.time&&console.timeEnd("inline parsing"),this.doc},On=An}),Pn=F((t,e)=>{var n=(En(),g(Ke));e.exports={Parser:n.Parser||n.default||n}});return Pn()})();function protectBlockBody(f){return f.split(`
`).map(function(v){return v.replace(/^([ \t]*)(,*)(\*|#\+)/,"$1$2,$3")}).join(`
`)}function codeSpan(f){return f.indexOf("=")===-1?"="+f+"=":f.indexOf("~")===-1?"~"+f+"~":f}function escapeCell(f){return String(f).replace(/\|/g,"\\|")}function linkType(f){return/^[a-zA-Z][a-zA-Z0-9+.-]*:/.test(f)||/^[/~#]/.test(f)||/^\.\.?\//.test(f)}function escapeLinkPath(f){var v=String(f);return v&&!linkType(v)&&(v="file:"+v),v.replace(/([\[\]\\])/g,"\\$1")}function fnLabel(f){return String(
f).trim().toLowerCase().replace(/[^a-z0-9_-]+/g,"-").replace(/^-+|-+$/g,"")||"fn"}function renderOrg(f,v){for(var H={},W={},it=f.walker(),U,z,F,xt;U=it.next();)if(!(!U.entering||U.node.type!=="footnote_definition")&&(z=U.node._label,H[z]===void 0)){for(F=fnLabel(z),xt=1;W[F];)xt++,F=fnLabel(z)+"-"+xt;W[F]=1,H[z]=F}function rt(p){return H[p]!==void 0?H[p]:null}renderOrg.warn||(renderOrg.warn={});var N=[],
g="",st=[],$=[],I=0,at=0,D=0,m=0,_=!0,yt=!1,lt=0,ot=!1,q=!1,ct=0,ht=0,Y=0,G=!1,V="",ut=!1,pt=!1,ft=!1,tt=-1;function Z(p){var k=renderOrg.warn[p]||(renderOrg.warn[p]=[]),P=N.length+1;k[k.length-1]!==P&&k.push(P)}function x(){return st.join("")}function dt(p,k,P){return p!==k&&Z(P),k}function h(p){p&&(g+=p,_=!1)}function b(){$.length&&(g=g.replace(/^(\s*(?:-|\d+\.) )\[x\] /,"$1[X] ")),!ut&&/^\*+\s/.
test(g)&&Z("heading"),!pt&&!ft&&/^[ \t]*#(\s|$)/.test(g)&&Z("comment"),G&&/^[ \t]*#\+(BEGIN|END)_/i.test(g)&&Z("stray block delimiter"),/\[\[[^\]]*\]\]/.test(V)&&Z("[[ ]] read as an Org link"),G=!1,V="",ut=!1,pt=!1,N.push(g),g="",_=!0}function A(){g!==""&&b()}function et(){N.length&&N[N.length-1]!==""&&N.push("")}function B(p){var k=p.sourcepos;if(!k){et();return}lt&&k[0][0]>lt+1&&et()}function E(p){
p.sourcepos&&(lt=p.sourcepos[1][0])}function jt(p){var k=ot?dt(p,v.escapeCell(p),"\\| in a table cell"):p;G=!0,V+=k,h(k)}function At(){var p=tt>=0?g.slice(tt):"";(p.indexOf("]]")!==-1||p.slice(-1)==="]")&&Z("]] in a link description"),tt=-1,h("]]")}function _t(p){ft=!0,p.replace(/\n$/,"").split(`
`).forEach(function(k){h(x()+k),b()}),ft=!1}function Et(p){var k=p.replace(/\n$/,""),P=/^ {0,3}<!--/.exec(k);if(!P)return!1;var R=k.indexOf("-->");if(R!==-1&&!/^\s*$/.test(k.slice(R+3)))return!1;var zt=k.slice(P[0].length,R===-1?void 0:R);return zt.split(`
`).forEach(function(vt){h(x()+(vt?"# "+vt:"#")),pt=!0,b()}),!0}for(var Pt=f.walker(),O,c,gt;O=Pt.next();)switch(c=O.node,gt=c.type,gt){case"text":at===0&&jt(c.literal,c);break;case"softbreak":if(q){h(" ");break}if(Y){h(" ");break}b(),h(x()),_=!0;break;case"linebreak":h("\\\\"),b(),h(x()),_=!0;break;case"code":var X=c.literal,Q,nt;ot&&X.indexOf("|")!==-1?(Q=dt(X,v.escapeCell(X),"\\| in a table cell"),
nt=!0):(Q=v.codeSpan(X),nt=Q===X),G=!0,nt&&(V+=Q),h(Q);break;case"emph":h("/");break;case"footnote_definition":O.entering?(A(),c.prev&&c.prev.type==="footnote_definition"?et():B(c),h(x()+"[fn:"+rt(c._label)+"] "),q=!0):(q=!1,g=g.replace(/[ \t]+$/,""),b(),et(),E(c));break;case"footnote_reference":h(rt(c._label)?"[fn:"+rt(c._label)+"]":"[^"+c._label+"]");break;case"table":O.entering?(A(),B(c)):E(c);
break;case"table_row":if(O.entering)h(x()+"|");else if(b(),c._isHeading){for(var mt=[],Lt=[],Nt=!1,M=c.firstChild;M;)mt.push("----"),Lt.push(M._align==="center"?" <c> ":M._align==="right"?" <r> ":M._align==="left"?" <l> ":" "),M._align&&(Nt=!0),M=M.next;h(x()+"|"+mt.join("+")+"|"),b(),Nt&&(h(x()+"|"+Lt.join("|")+"|"),b())}break;case"table_cell":ot=O.entering,O.entering?h(" "):h(" |");break;case"st\
rikethrough":h("+");break;case"strong":h("*");break;case"link":case"image":O.entering?(I>0?(h(v.escapeLinkPath(c.destination)),at++):c.destination&&!c.firstChild?(h("[["+v.escapeLinkPath(c.destination)),m++):!c.destination||c.destination[0]==="#"?D++:(h("[["+v.escapeLinkPath(c.destination)+"]["),I===0&&(tt=g.length)),I++):(I--,I>0?at--:D?D--:m?(m--,h("]]")):At());break;case"html_inline":h("@@html:"+
c.literal+"@@");break;case"html_block":A(),B(c),Et(c.literal)||(h(x()+"#+BEGIN_EXPORT html"),b(),_t(v.protectBlockBody(c.literal)),h(x()+"#+END_EXPORT"),b()),E(c);break;case"paragraph":O.entering?(q||B(c),g===""&&(g+=x()),_=!0,yt=!0):(q?h(" "):b(),yt=!1,E(c));break;case"heading":O.entering?(Y++,ht=ct||$.length,ht?($.length||B(c),g===""&&(g+=x()),h("*")):(A(),B(c),h("*".repeat(c.level)+" "),ut=!0)):
(ht&&(g.slice(-1)==="*"?g=g.slice(0,-1):h("*")),Y--,b(),E(c));break;case"code_block":A(),B(c);var wt=(c.info||"").trim().split(/[\s{}]+/).filter(Boolean)[0]||"";h(x()+(wt?"#+BEGIN_SRC "+wt:"#+BEGIN_EXAMPLE")),b(),_t(v.protectBlockBody(c.literal)),h(x()+(wt?"#+END_SRC":"#+END_EXAMPLE")),b(),E(c);break;case"thematic_break":A(),B(c),h(x()+"-----"),b(),E(c);break;case"block_quote":O.entering?(A(),B(c),
h(x()+"#+BEGIN_QUOTE"),b(),ct++,c.sourcepos&&(lt=c.sourcepos[0][0])):(ct--,A(),h(x()+"#+END_QUOTE"),b(),E(c));break;case"list":O.entering?($.length||B(c),$.push({ordered:c.listType==="ordered",n:c.listStart===null||c.listStart===void 0?1:c.listStart,first:!0})):($.pop(),E(c));break;case"item":if(O.entering){A();var S=$[$.length-1],T;S.ordered?(T=S.n+". ",S.first&&S.n!==1&&(T+="[@"+S.n+"] "),S.n++):
T="- ",S.first=!1,g+=x()+T,st.push(" ".repeat(T.length)),_=!0}else st.pop();break;default:break}for(g!==""&&b();N.length&&N[0]==="";)N.shift();for(;N.length&&N[N.length-1]==="";)N.pop();return N.join(`
`)}function md2org(f){if(typeof f!="string"&&(f=String(f??"")),f==="")return"";renderOrg.warn={};var v=new __cmark.Parser({sourcepos:!0}),H={codeSpan,escapeLinkPath,protectBlockBody,escapeCell},W=renderOrg(v.parse(f),H),it=Object.keys(renderOrg.warn);return it.length?W+`

# md2org warnings:
`+it.map(function(U){return"# "+U+": line "+renderOrg.warn[U].join(", ")}).join(`
`):W}

try{var i=$text==null?"":String($text);if(i=="")return "⚠️ md2org: no input — set the Text field to Clipboard";var o=md2org(i);return o==""?"⚠️ md2org: result was empty":o}catch(e){return "⚠️ md2org: "+(e&&e.message||e)}
